### ISSUE TITLE
Feature Request: Customer portal

### ISSUE THREAD

**Issue by Shootify** [johnnyq/itflow#104]
implement customer portal so they can have access of invoices, quotes, tickets and possible documentation?

**Comment by johnnyq** [comment]
This is partially done, when an invoice gets emailed to the client. A Specially crafted link will be sent to them so they can use that link to view past invoices as well. Im not sure if we will add documentation and ticket access. Although we will make this easily exportable to PDF and Spreadsheet mainly for customer disconnects.

**Comment by johnnyq** [comment]
Closing this as client already have access to account info invoices quotes etc. Documentation can be exported via PDF and sent to them when needed.
