### ISSUE TITLE
Feature Request: Add photo field per company

### ISSUE THREAD

**Issue by krisleslie** [johnnyq/itflow#105]
Some of the companies I'm sure we will deal with have a respective logo. So I think adding a logo field and then having it on the viewable report for that company would add a little bit of branding and value.  I noticed each contact already has a photo field enabled.

**Comment by krisleslie** [comment]
Also this is Kris Leslie from Tom Lawrence IT Forums! Again thank you for doing what you do best!

**Comment by johnnyq** [comment]
Good Idea will do! and nice to meet you Kris Leslie =] Thanks again

**Comment by johnnyq** [comment]
Decided not to add this for now maybe in the future as there are many tasks that take priority.
