### ISSUE TITLE
Assets not showing after adding one

### ISSUE THREAD

**Issue by ModernAesthetics** [johnnyq/itflow#115]
When I add a new asset it does not appear under assets.
2 assets I've added that had logins add under logins but I would assume it should also show under assets.

**Comment by johnnyq** [comment]
Hi @ModernAesthetics good point. Assets was supposed to be your own company assets and not show the assets of clients. Although I will update this to be global so client assets show up under assets on the main side nav.

**Comment by johnnyq** [comment]
This has been fixed All Assets will show under assets to edit or delete assets you will need to access the client details.
