### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dinger1986** [johnnyq/itflow#116]
Is it ok to setup a demo?

Also keen to write an install script for this as well!

All ok?

**Comment by dinger1986** [comment]
install script written last night and tested today, working fine with a subdomain

**Comment by johnnyq** [comment]
Id be very interested in your install script and yes its okay to setup a demo. Although we already have a demo at demo.itflow.org user is demo@demo
password is demo

**Comment by johnnyq** [comment]
I need to update the documentation to reflect this project has a name and a website that is in development as well as a demo. Keeping this open for tracking.

**Comment by johnnyq** [comment]
Updated Documentation

**Comment by johnnyq** [comment]
d39e2d9bfa7625110d23ca65731d085ae560a146

Thanks @dinger1986

**Comment by dinger1986** [comment]
Script is here https://github.com/dinger1986/dvis/blob/main/itflowcrminstall.sh

Feel free to take it and move it somewhere else

**Comment by johnnyq** [comment]
Wow nicely done @dinger1986 I will fork this thank you so much for your contribution

**Comment by dinger1986** [comment]
just realised a typo so please check the script again, theres a reference to PITTCRM which should have been changed to ITFlow under the db user creation

**Comment by johnnyq** [comment]
I saw that, I forked your code and made those changes. This will come into good use.
