### ISSUE TITLE
Feature Request: have time recording in tickets

### ISSUE THREAD

**Issue by dinger1986** [johnnyq/itflow#118]
For my busienss we are recording time so currently use Anuko Time Track but would like to look at other options, the reason we use Anuko is it has a very simple start and stop button so recording time is so simple. For my business as the majority of work is time in line recording time is critical

**Comment by johnnyq** [comment]
@dinger1986 Good idea, will add that feature down the line Thank you =]

**Comment by johnnyq** [comment]
@dinger1986 we are going to close this for now, as we recommend to use an external app or program as you for your timer. Were working on minimizing the code even further
