### ISSUE TITLE
Feature Request: Add 2FA Checkbox and Type to Client Logins List 

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#119]
Feature: Add 2FA Checkbox and 2FA Type to Logins

**Comment by aftechro** [comment]
For the logins, can you add the OTP under the logins and mask the password and have a show password and show otp

![image](https://user-images.githubusercontent.com/38830718/112542107-1750e180-8dac-11eb-8a1e-bf215b4792e5.png)

![image](https://user-images.githubusercontent.com/38830718/112542181-29328480-8dac-11eb-8e04-f3665dc31492.png)

![image](https://user-images.githubusercontent.com/38830718/112542346-5e3ed700-8dac-11eb-84e3-fa78a6875ff8.png)

80% of logins are secured with 2fa/otp these days :D

**Comment by johnnyq** [comment]
@aftechro Great idea ill get this function added

**Comment by johnnyq** [comment]
OTP Has been Added cdcd22ae6fb189749654ff05f080352d11eace71

**Comment by johnnyq** [comment]
This has been added Closing
