### ISSUE TITLE
Feature Request: User Permissions

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#122]
Define user permissions

- **Global Admin** Access to all Companies
- **Admin** Access to Specified Company
- **Accounting** Access to Invoice Quotes Payments, Accounts  etc)
- **IT** (Access to customer IT Docs)
- Any Other Ideas?

**Comment by afsound** [comment]
From the point of it managed company (who manage it services for more clients), where there`s a owner, staff and clients i would do something like this: 

**Global admin** - owner of company - access to all features and configurations

**Accounting** - as you put it

**IT Admin** - access to: assets, documents, configurations  - adding/editing data of existing/new companies  (this for staff of the it managed company)

**Client access** (internal manager/primary contact/it person of the client) - view the assets and bills and generate reports for their needs.

**Comment by johnnyq** [comment]
Good Idea I think we should also consider adding another group called contractor and have access limitations based off the selected customers.

**Comment by johnnyq** [comment]
Initial work has begun 88933e09f78e75265d5f03866d66773d71a34c2f

**Comment by wrongecho** [comment]
Closing against #321 - plans for access & a client potal
