### ISSUE TITLE
Feature Request: Integration with TacticalRMM and MeshCentral

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#123]
Would like to integrate these two amazing Free Open Source IT Projects. Please include ideas you may have on what your would like integrated between them

**Comment by dinger1986** [comment]
Have you spoken to White about this? 

Sounds amazing!!

**Comment by johnnyq** [comment]
@dinger1986 I have not but i'm not sure if there really needs to be any integration so i'm going to close this one for now
