### ISSUE TITLE
Feature: Ability to add different tax rates for different countries

### ISSUE THREAD

**Issue by Nymall** [johnnyq/itflow#127]
We're up here in canada, and so far we're loving playing around with your project! However, we have a complex sales tax system up here, and we need to add different tax rastes for different provinces(or if we're dealing with the states). The ability to edit tax rates from the options panel would be wonderful.

**Comment by johnnyq** [comment]
@Nymall thanks so much, i'm glad the project can be of use to you and your company, this is why I enjoy developing this project. We will add this feature this week. I appreciate the merge and is a a good band aide. We will add the taxes under categories.

**Comment by johnnyq** [comment]
@Nymall This feature has been added. A new table called taxes will need to be created in SQL the structure is located in the db.sql file.

a2848fad09dc8d35f4ae1aa355cfe324b9cc6c8b
