### ISSUE TITLE
Bug: Rich text from the rich text editor is not supported on the ticket window

### ISSUE THREAD

**Issue by Nymall** [johnnyq/itflow#128]
Any ticket added with special formatting will have the special formatting removed, which can be frustraiting and make readability problems.

**Comment by johnnyq** [comment]
@Nymall good call we will add this functionality this week

**Comment by johnnyq** [comment]
Hi @Nymall this has been fixed as well =]

74efc339ef2073a6e23a8b43c3d0dee856c3f267
