### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mrboingo** [johnnyq/itflow#130]
I have a brand new Ubuntu 20.04 server with LAMP (maraidb) and pulled in the clone.  The Start install keeps looping.  It asks for the db info then asks to create a new user and company but once you click on the install button it brings you back to the beginning.  Over and over. I've tried about 3 times already.

**Comment by johnnyq** [comment]
hello @mrboingo once you pull the repo set permission recursively on the pulled files example chown -R www-data:www-data /var/www/itflow

**Comment by johnnyq** [comment]
also check out this installtion script written by @dpinger1986 

https://github.com/johnnyq/dvis/blob/main/itflowcrminstall.sh

**Comment by mrboingo** [comment]
Thanks, the chown took care of it.  I appreciate the help!!
