### ISSUE TITLE
email invoice

### ISSUE THREAD

**Issue by afsound** [johnnyq/itflow#132]
When i sending invoice to email it will send a link but the link is not accessible

![image](https://user-images.githubusercontent.com/38830718/105626721-8f8d3c00-5e29-11eb-8138-098030edbf3f.png)

![image](https://user-images.githubusercontent.com/38830718/105626750-c2cfcb00-5e29-11eb-9c51-409ee2a1b3b7.png)

any chance to send this invoices as pdf format as attachement rather then a link url?

**Comment by johnnyq** [comment]
Hi @afsound that is strange and should work it looks like it may be an http:// link and not an https://
I know you blanked out the first part of the url for security purposes but the first part should look something like this https://itflow.example.com/guest_view_invoice.php

**Comment by afsound** [comment]
Hi Johnny,

That`s great, installed the ssl on my end, and works like a charm!
