### ISSUE TITLE
link service to client

### ISSUE THREAD

**Issue by afsound** [johnnyq/itflow#133]
how can i set services to be shown in the services section of the client

![image](https://user-images.githubusercontent.com/38830718/105629783-03850f80-5e3d-11eb-88ee-70c73cad96b5.png)

**Comment by johnnyq** [comment]
Hi @afsound the services section currently does nothing, I implemented it for filler to test the top bar this will be removed in a later commit.

**Comment by johnnyq** [comment]
Closing for now
