### ISSUE TITLE
adding trips error

### ISSUE THREAD

**Issue by aftechro** [johnnyq/itflow#134]
when trying to add trips as call out jobs, i have this error

![image](https://user-images.githubusercontent.com/38830718/105637473-9d60b280-5e65-11eb-8f1d-07b512e96bf1.png)

on the back end it shows that the trip was added, but after that, nothing shows on the trips page.

this would be handy for the call out jobs

an another note, i noticed that i cannot use google account as the smtp mail, for some reason not working. allowed less secure apps, try different methods but not working. so instead i used something else.

**Comment by johnnyq** [comment]
Hi @afsound I wasn't able to replicate in the latest commit. There are 2 ways to add trips one globally and one through the client. 

Is it not working both ways?

Excellent screenshot, although the errors are mainly due to undefined vars which you will receive alot of. I'll work on cleaning this up before release.

Keep up the bug reporting this helps quite a bit =]

**Comment by afsound** [comment]
Hi Johnny.

It doesnt works both ways.

**Comment by afsound** [comment]
![image](https://user-images.githubusercontent.com/38830718/105836612-55f13800-5fc5-11eb-8d80-770aaaa96c13.png)

is just shows 1 records, doesnt matter how many records i`ll input, that number remain as it is.
and no data to be shown

**Comment by johnnyq** [comment]
@afsound I started doing alot of reworking especially in trips can you confirm if this working, you may have to reinstall again as there has been major backend updates

**Comment by afsound** [comment]
Hi Johnny,

Still cant get the trips to work, but probably something on my end, test them on your demo url and works fine there, but not sure why wont work on my host. I`ll have to check if is not something to do with the host itself. running on nginx with php7.4

**Comment by johnnyq** [comment]
hmmm that what I am running too with mariadb see if theres anything new in the php log. I cleaned up alor of the errors that were outputting there so it should be much easier to find real errors.

**Comment by johnnyq** [comment]
@afsound Any recent luck? or is this still a problem for you?

**Comment by afsound** [comment]
Hi mate, i`ll have to use the new updates you made and let you know if something changed.

**Comment by afsound** [comment]
For some reason there`s no trips table in my db

![image](https://user-images.githubusercontent.com/38830718/108041330-4601cc80-7036-11eb-8b78-59102a095c95.png)

**Comment by aftechro** [comment]
any advise for this? for some reason wont create trips data base. just removed everything and added the project again with latest updates, but still same... no trips table created.

**Comment by johnnyq** [comment]
@aftechro that is really strange.

Have you completely dropped the DB and recreated it then reinstall or did you just reinstall without dropping the DB?

Linux Distro?
Are you using MySQL or MariaDB? and version?
PHP Version?

I can do a remote session with you on install to see what might be causing it.

**Comment by aftechro** [comment]
Hi Johny,

I`ve downloaded the sql from the demo site and create the trips table on my end
 
    CREATE TABLE `trips` (
  `trip_id` int(11) NOT NULL AUTO_INCREMENT,
  `trip_date` date NOT NULL,
  `trip_purpose` varchar(200) NOT NULL,
  `trip_source` varchar(200) NOT NULL,
  `trip_destination` varchar(200) NOT NULL,
  `trip_start_odometer` int(11) DEFAULT NULL,
  `trip_end_odmeter` int(11) DEFAULT NULL,
  `trip_miles` float(15,1) NOT NULL,
  `round_trip` int(1) NOT NULL,
  `trip_created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `trip_updated_at` datetime DEFAULT NULL,
  `trip_archived_at` datetime DEFAULT NULL,
  `client_id` int(11) DEFAULT NULL,
  `company_id` int(11) NOT NULL,
  PRIMARY KEY (`trip_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

without the INSERT INTO trips VALUES("1","2021-03-09","Service Visit","My Office","Client Office","","","45.0","1","2021-03-09 11:05:52","","","1","1");

then i took this line   `trip_created_at` datetime NOT NULL DEFAULT current_timestamp(), as gave some error and worked.


So now i`m able to input and save data into the trips.

**Comment by johnnyq** [comment]
@aftechro You found it!! Great Job this has been fixed in the latest commits thanks to you!! It seemed to affect MYSQL 8 users and not MariaDB as this was why I was not affected. Closing for now thanks again
