### ISSUE TITLE
Future update: translation

### ISSUE THREAD

**Issue by afsound** [johnnyq/itflow#135]
Would be handy to have the invoices sent in the language that needed.

I can help you out with the Romanian translation.

**Comment by johnnyq** [comment]
that would be fantastic! although I have to work out the logistics and implementing locale (Currency, timezone language, formats etc) properly into code. This however will be major task and would require quite a bit of code manipulation in all areas. We are not quite ready to tackle this just yet. We want to push out 1.0 stable soon, maybe we'll shoot for 2.0 for the locales. Im going to close this for now.
