### ISSUE TITLE
Colo(u)r picker history

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#145]
It would be good if the colour picker (or color picker if you can't spell properly...) could have a history, or recently used, or even retain the last selected colour to make it easier to colourise things.

On the demo account I decided to colour all expense categories one colour, income another, payment types in a third. etc. etc. I could have remembered the RGB for each but my memory is terrible, I could have written it down, but I figured the "best" solution would be for it to remember.

Maybe have a 4 x 4 grid of user defined / theme colours?

**Comment by johnnyq** [comment]
Good idea @gwes Ill work on this one. Keep them flowing your reports are extremely helpful.

**Comment by johnnyq** [comment]
@gwes This has been done! let me know if you like the implementation.
By default it give you 20 colors to work with for each category Type and will only show the colors available when adding or editing categories. 

08fcea5f432c6b05fd76a7269142645432a162ae
