### ISSUE TITLE
Quotes with multiple categories

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#147]
Generally if I am doing a quote for a customer it would be made up of multiple lines and those lines could be for different classifications of "things". For example ;
10 off Computers
8 off Copies of Office
2 off Copies of Autocad
24 off hours installation and configuration time

I would want to have different categories for each line so that in the future I can track my profit by, for example, hardware sales.

I've not used the system enough to know if this is possible a different way but it's an observation on how it appears to work so far.

**Comment by johnnyq** [comment]
We do have categories for invoices and quotes however its for the entire invoice / quote. Although this can be a problem 

for example

you have 2 service Income categories Computers and Service.
You create an invoice and mark the category as computer
The following line items are in the invoice

Data Transfer
Dell Latitude Laptop

We have both a Service and a Computer Category.

The best way currently around this is to create separate invoices for the income category

so in this case you would create 2 invoices 1 for the service and 1 for the computer.

We may add this later down the line. ill keep this open

**Comment by gwes** [comment]
That's a work around for sure, I used to to that with an older accounting package I used a few years ago. I'm aware that making that change would be quite a bit of code re-working!

**Comment by johnnyq** [comment]
I'm going to work on this one, ill take categories off invoices and put onto into invoice items. This will make sense for income tax purposes.

**Comment by johnnyq** [comment]
After much debating we are going to keep separate invoice and quotes for separate categories as this is much easier to implement and track.
