### ISSUE TITLE
Tax type lost when editing a line in a quote

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#148]
If you open a line item on a quote to edit it, the tax dropdown does not seem to load the current setting so if you do not correct it and just hit save then no tax is applied to that line going forward (unless you edit again and correct obviously.)

**Comment by johnnyq** [comment]
looks like a bug as well will work this out thanks =]

**Comment by johnnyq** [comment]
We implemented tax id to items tables and updated it in the necessary places. Also if you have a recurring invoice and the tax rate percent changes the next time it send out the invoice it will update the invoice with the new rate was well as the recurring template. Please test extensively and report any bugs thanks

632714cd17980faa20fbca894beec9e41d8c56e4
