### ISSUE TITLE
Image not found icon in top left of quote when generating pdf

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#149]
I've just generated a PDF from a quote I made (on the demo system) and there is an "image not found" red cross in the top left hand corner.

I am assuming that this should be a company logo and that there is not one configured in the demo system. Might be good to check if this is set and if not to display nothing.

Assuming I'm correct its probably not actually a massive issue as most people will upload a logo.

**Comment by johnnyq** [comment]
looks like a bug ill get this one fixed up thanks for reporting

**Comment by johnnyq** [comment]
Fixed we switched to pdfmake
