### ISSUE TITLE
Should you be able to edit a quote once it's been "approved"

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#153]
Hey, I'm back... sorry.

At present you are able to have a quote approved and then after it's been approved you can change it.

Whilst I can see that this would be good (and my current in house quote system also allows this) I have always thought that it would be better to force an amendment to be a "new" quote QUO-001 becomes QUO-001-A for example and if you require the customer to approve it then they could be notified and asked to re-confirm.

It makes it a bit of a pain in the arse if you need to make a small change that you know a customer will be ok with but if you are going to the trouble of having an approval process then it probably ought to lock the thing that was approved.

Thoughts?

**Comment by johnnyq** [comment]
I agree, only allow editing in draft only or if you are admin. Ill get on this The Copy Quote function can be used to duplicate an existing quote that has been declined.

**Comment by johnnyq** [comment]
I wonder if we should rename Copy to Duplicate. What do you think @gwes ?

**Comment by gwes** [comment]
Duplicate is the term I use in my current system. It then gives the option to select customer to duplicate too (with the current customer selected as default).

**Comment by wrongecho** [comment]
Quotes items can now no longer be edited once approved. Quotes can be duplicated and turned into invoices. Closing! :)
