### ISSUE TITLE
Action button on the quotes view could change "approve" to "invoice" if the quote has been approved already

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#154]
What the subject says really...
At the moment you can approve a quote by pressing the actions button. Once the invoice has been approved that option could be changed to be an "invoice" action. Saves a couple of clicks potentially.

**Comment by johnnyq** [comment]
All fixed, We removed approve and reject on the list view can only be accessed via quote details view. Thank you for your feed back.

d90c7e466461e685f5f77224728ec269414e3ff1
