### ISSUE TITLE
Invoiced quote should probably dissapear / change state

### ISSUE THREAD

**Issue by gwes** [johnnyq/itflow#155]
Once a quote has been invoiced I feel like the original quote should change state so that it can not accidentally be invoiced a second time. Maybe it disappears from the main quote view or status changes to Invoiced and it moves below the other quotes?

**Comment by johnnyq** [comment]
This has been done we removed actions like approve on the list view and kept them only to quote details view. Also renamed Approved to Accepted and Reject to Declined. Added invoiced status, let me know if it works good or if it needs any further improvements, Thank you for your feedback.

d90c7e466461e685f5f77224728ec269414e3ff1
