### ISSUE TITLE
Bug: Implement Non Destructive Deletion to prevent DB link breaking

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#157]
for example if you remove a category linked to an expense, it will break expenses, i'll use this as template for all the items that should not have delete.

- Taxes
- Categories
- Users
- Companies
- Vendors
- Accounts

**Comment by gwes** [comment]
Add an archived (timestamp) column to the DB and only show items where archived == "" in the the UI when you are changing something. That way it can still display historical items but allows you to keep the current list clean.

Maybe change the wording from "delete" to "archive" as well but from the end users perspective you have deleted it, it doesn't show up when you add a new item but it will when you view something historical.

This also gives you a get out of jail card in case of accidents. A show archived button subtly hidden somewhere.

**Comment by johnnyq** [comment]
good idea I may accomplish this by creating
a deleted_at field with a timestamp

then hide anything with a deleted_at timestamp.

Perfect ill get to this

**Comment by johnnyq** [comment]
Non Destructive Deleting has begun DB Structure Updated

2ea809b4e7b4ca1e3dba34f48870761144e0dbf8

**Comment by gwes** [comment]
But only hide it when creating new or you are editing an item dated after the deletion date. If you are editing an item from before the deletion date then you should still see it. Probably...

**Comment by johnnyq** [comment]
Excellent Idea!! Ill use both your ideas in the code Thanks 

Also I named the field names archived_at I agree archive is much better.

Ill work on this now

**Comment by johnnyq** [comment]
It has been done

**Comment by johnnyq** [comment]
This is now complete, on the most crucial items let me know if there should be any changes or bugs
