### ISSUE TITLE
Get payments by card on invoice

### ISSUE THREAD

**Issue by afsound** [johnnyq/itflow#167]
Hi Johnny,

not an issue, but a suggestion

Here`s another thing that can be integrated on the invoicing url generated: either paypal or stripe to get the option to customer or to account manager to pay/charged with credit card.

![image](https://user-images.githubusercontent.com/38830718/107658685-49840500-6c7e-11eb-8afa-8f784dadd22c.png)

Let me know what you think about this?

**Comment by johnnyq** [comment]
hi @afsound This is currently being implemented hopefully by the beginning of next week. We are focusing on strip integration at the moment
