### ISSUE TITLE
BUG: Do not display Send Email option if Mail is not configured

### ISSUE THREAD

**Issue by Shootify** [johnnyq/itflow#171]
when creating event and saving sometimes goes blank screen, same when check send/email event. 
cheers

**Comment by johnnyq** [comment]
@Shootify If you don't have mail configured under settings -> Mail and check the box send email event it will do what you described. I think I may hide the email event if mail is not configured to reduce the confusion. Thanks for pointing this out

**Comment by johnnyq** [comment]
Looks like this is also affecting email Invoices/quotes and Payment Receipts

**Comment by johnnyq** [comment]
Done

d7101cb5d65b754864a850f9ed860f89f5ab35c9
