### ISSUE TITLE
Feature: Ticket Assignment

### ISSUE THREAD

**Issue by shulemmosko** [johnnyq/itflow#172]

**Comment by johnnyq** [comment]
No not currently, but I will add that feature to the list ill keep this open for tracking, thanks

**Comment by johnnyq** [comment]
Initial work has begun
e547a7678049649db1c3710d78bf6b66277050e9

**Comment by johnnyq** [comment]
complete 131e04915b1505ec46bf4a0ea0dcdb7524ab0797
