### ISSUE TITLE
Records not displaying on fresh install

### ISSUE THREAD

**Issue by Malcharias25** [johnnyq/itflow#173]
OS: Ubuntu Server 20.04 LTS
DB: MySQL 8.0.23-0
Build: afkjgjfshgkfjg763g43g (??)
Web: Apache2

Problem:
Clean install of Ubuntu server, installed Apache/PHP/MySQL and configured using commands outlined in DVIS install script. Setup completed successfully, login to Admin account successful, however attempting to populate information intermittently fails to display. 

Example: 
1. Created new Client in Clients page. Clients page remains blank after creation, however New Clients Dashboard panel updates to show new client, and clicking in New Clients Dashboard shows the client.
2. Create new asset in Client that includes login information. Asset does not display in Assets panel, however Login information DOES appear in the Logins panel (not linked to any asset.)
3. Create new Trip for a client. Trip created and Trips heading updates to show "1", however the page shows no records.

Obviously, while I'd like to test this for possible deployment for our company, but in it's current state I can not recommend this as a viable solution.

Any input you can provide as to the nature of this issue and how to resolve it would be appreciated.

**Comment by Malcharias25** [comment]
After some testing, it appears that I'm running into some issues (at least in part) with updates from the webUI not being written to the SQL backend.

When creating some entries (clients for instance,) SQL tables are updated. Attempting to add an asset however fails to create an entry in the database. If I manually create an entry in the Assets table, (using the same login/password used during initial setup,) the record IS displayed in the Assets page for that client. Attempting to update the injected entry via the webUI also fails. ​

I have  updated permissions on the web root folder to "www-data:www-data" as recommended, and I pulled the latest version from the git. Any thoughts on where to proceed from here would be appreciated, as this looks to be an excellent documentation solution for our needs. 

Thanks in advance!

**Comment by johnnyq** [comment]
@Malcharias25 Try installing a fresh copy with MariaDB instead of MySQL Im curious if you get different results

**Comment by Malcharias25** [comment]
@johnnyq Good call! After spinning up a new VM, and installing using MariaDB all entries seem to be recorded and displayed as expected - at least for the first few entries. I'll do some more testing on my end, but this appears to be resolved.

Thanks for your help!

**Comment by johnnyq** [comment]
Excellent!! I'm still curious why things are not working well with MySQL ill do some more testing in that realm thanks for your feedback
