### ISSUE TITLE
Adding a document with image under client doesn't work every time

### ISSUE THREAD

**Issue by grelbar** [johnnyq/itflow#177]
(tested on the demo site )

Creating a document under a client with a picture and some text says it has created a new document but it doesn't appear in the list. 

![image](https://user-images.githubusercontent.com/81080174/111901948-91e3cf00-8a43-11eb-99a2-277aa3ac2f3d.png)

![image](https://user-images.githubusercontent.com/81080174/111901956-990add00-8a43-11eb-8f81-d853da64d40b.png)

Creating a document with no image works as intended and shows up on the list of documents. 

Creating a document with just text first, and then adding the same picture late also does not work, the image is not saved in the document. Tested with various image sizes, tested using the file upload function instead of copy-paste, but the same result.

**Comment by johnnyq** [comment]
Nice Bug Report @grelbar I think i found the issue. Currently the Database field is set to text which is limited I will change this to longtext and that should correct it. In fact ill change it in multiple parts as this more than likely affects other fields as well.

**Comment by johnnyq** [comment]
Fixed fed532153aec89c37b73dbf93b2e28d012f1b111
will update the demo site soon
Thanks @grelbar
