### ISSUE TITLE
Feature request: RTL support

### ISSUE THREAD

**Issue by DjMagicFingers** [johnnyq/itflow#182]
Great initiative for something every MSP will need.

I am asking to add the ability to use the product with an RTL (Right To Left) language like Hebrew.

I do understand that transforming everything to RTL is a huge project so even if that is not possible right now, a good starting step towards full RTL support would be the option to align text in various locations to the right (not only justify but also align!).

The most important fields where RTL alignment is crucial are:
1. Ticket subject
2. Ticket details
3. Document name
4. Document boddy
5. Event title
6. Trip purpose
7. Reoccurring scope
8. Contact name
9. Product name
10. Product description

And more...

**Comment by johnnyq** [comment]
Closing this for now, pull request are welcome.
