### ISSUE TITLE
Feature request: Multi currency support

### ISSUE THREAD

**Issue by DjMagicFingers** [johnnyq/itflow#184]
We operate from Israel (that uses ILS - israeli Shekel) but we provide support for clients world wide, where different clients use different currencies.
I would like to request a way to be able to work with multi currencies on one sales document.

For example, when I build different products, they can have different currencies - a CPU can be sold in USD, motherboard in ILS and labor in EUR.

If I want to produce a sales document like a price offer or an invoice, I would like to "collect" the different products that are originally set up with different currencies and have the system calculate the total price for the document based on the currency that the client is defined to use - in this example - let's say USD - so the system will convert ILS and EUR to USD and produce a well priced document.

I understand that this feature will have to rely on a currency conversion services - that can also be an enhancement - to be able to update daily currency for selected currencies.

**Comment by iamkhris** [comment]
I will throw my vote on this as well.  I'm in Canada and there is no option to select CDN for currency.

I've been using a program called Invoice Ninja which integrates with Open Exchange Rates.  You sign up with them, get an App ID, plug that into Invoice Ninja, and once a day it updates the various currency exchange rates, providing multi-currency support.

**Comment by aftechro** [comment]
I can say only that: Work in progress :d

**Comment by iamkhris** [comment]
> I can say only that: Work in progress :d

Agreed, and your work is impressive thus far so I'm confident this is something we will see in a future release. :)

**Comment by aftechro** [comment]
That`s Johnny doing awesome work implementing all our ideas.
I`ve done some custom changes on my end which works fine, and suggest them to Johnny which will be added in the future.

**Comment by wrongecho** [comment]
Multiple currencies are now supported! Johnny has used [NumberFormatter](https://www.php.net/manual/en/numberformatter.formatcurrency.php) to ensure the formatting is correct too (i.e. symbol before or after the amount)!

![currency](https://user-images.githubusercontent.com/32306651/155877261-0b71975c-6037-487e-b88a-c3c45cad9f69.png)
