### ISSUE TITLE
few changes

### ISSUE THREAD

**Issue by aftechro** [johnnyq/itflow#185]
Hi Johnny,

Hope you are well. Just playing around with the php files in trying to get some changes

So here what i managed so far

1. **DONE** add client name on the top along with back arrow, so that should be visible on which client you are working on

![image](https://user-images.githubusercontent.com/38830718/128593453-bcf7d54a-4c34-4922-aff4-d985b4405191.png)

           <a href="clients.php" class="nav-link">
            <i class="nav-icon fas fa-arrow-left"></i>
           <p>Back</p> | 
          <p><strong><?php echo $client_name; ?></strong></p>
          </a>
         
2. **STUCK** On client_logins.php added OTP data and add copy to clipboard icon for data to be copied, and hide the password content and add unmask icon

          <?php
      
          while($row = mysqli_fetch_array($sql)){
            $login_id = $row['login_id'];
            $login_name = $row['login_name'];
            $login_uri = $row['login_uri'];
            if(empty($login_uri)){
              $login_uri = "N/A";
            }
            $login_username = $row['login_username'];
            $login_password = $row['login_password'];
            **$login_OTP = $row['login_OTP'];**
            $login_note = $row['login_note'];
            $vendor_id = $row['vendor_id'];
            $asset_id = $row['asset_id'];
            $software_id = $row['software_id'];
      
          ?>

           <tr>
            <th><a class="text-secondary" href="?<?php echo $url_query_strings_sb; ?>&sb=login_name&o=<?php echo $disp; ?>">Name</a></th>
            <th><a class="text-secondary" href="?<?php echo $url_query_strings_sb; ?>&sb=login_uri&o=<?php echo $disp; ?>">URL/Host</a></th>
            <th><a class="text-secondary" href="?<?php echo $url_query_strings_sb; ?>&sb=login_username&o=<?php echo $disp; ?>">Username</a></th>
            <th>Password</th>
           <th>OTP</th>
            <th class="text-center">Action</th>
           </tr>

          <td><?php echo $login_uri; ?> **<i class="far fa-copy"></i>**</td>
          <td><?php echo $login_username; ?> **<i class="far fa-copy"></i>**</td>
          <td><?php echo $login_password; ?>  **<i class="far fa-eye" id=""></i> <i class="far fa-copy"></i>**</td>
          <td><?php echo $login_OTP; ?>  <i class="far fa-copy"></i></td>

![image](https://user-images.githubusercontent.com/38830718/128593483-52775754-322b-451d-bb16-a1f86e393871.png)

![image](https://user-images.githubusercontent.com/38830718/128593501-6d21f199-7c13-491f-a2bb-7667e1f94872.png)

3. add_domain_modal.php lines 35 and 60 changed to:

          $sql = mysqli_query($mysqli,"SELECT * FROM vendors ORDER BY vendor_name ASC");

so that shows all vendors, form general page as well as client vendors (changed menu to display Global vendors and Client vendors)

4. clients.php i added few lines that would show type of support client (maintenance/non-maintenance) and contract date started

![image](https://user-images.githubusercontent.com/38830718/128593436-058ec089-7abc-40c4-abd6-3203380d42a5.png)

                  <br>
            <small class="text-secondary"><i class="fas fa-handshake"></i> <b>SUPPORT: </b><span style="color:<?php echo ($client_referral=="Maintenance"?"green":"red");?>;"><?php echo $client_referral;?></span></small>
            <br>
            <small class="text-secondary"><b>Contract started: </b><?php echo $client_created_at; ?></small>

can be also used in client_nav.php, so the technician will see regardless of the section he is on, if client support maintenance or not, for fully or limited support 

![image](https://user-images.githubusercontent.com/38830718/128593972-5b265e4e-4206-458d-98d9-12049be04f73.png)

             <p>Back</p> | 
            <p><strong><?php echo $client_name; ?></strong></p>
           </a>
        
          <center><small class="text-secondary"><i class="fas fa-handshake"></i> <b>SUPPORT: </b><span style="color:<?php echo ($client_referral=="Maintenance"?"green":"red");?>;"><?php echo $client_referral;?></span></small>
         </center>

used client_referral for support type - but would be nice to have a separate field for it
also, contract started and contract ends another separate field

**the issues i have is on number 2, with the copy to clipboard and mask/unmask passwords** - couldn't make it to work, if you could have a look at that, that would be great. 

Thank you!

**Comment by johnnyq** [comment]
@aftechro Excellent Work!! The changes you made look Great!!

I really like showing the client's name on the Client Side NAV, this totally solves the issue of wondering if you are in the client section or the global section. 

I'm not sure if Global vendors will be that easy and yes your code will show all vendors however certain client logins and other DB links may cause issues along with specialized client specific vendor notes in which it will show for all clients. I will have to work on this a little bit to see a proper way to implement.

Maintenance and Contract Dates can be little tricky as we sell clients several different products such as VOIP, Managed Servers, Workstations Networks, Websites etc but don't do contracts per say. What I may end up doing is a separate contracts tables linked to the client. Some clients are not fully managed but we manage some things so that's where it can get tricky.

The placement of the password reveals and copy paste are fantastic!!! and I really like the way you implemented them. It will just take a little bit of JavaScript code to implement, which I should be able to do.

The OTP However is a whole Different ball game and I will have to think on how that is going to be implemented, maybe a checkbox to enable 2FA and an option to copy and paste the OTP code, but the problem really comes from the fact how make it function and work becuase I know the code will refresh every 60 secs and will have refresh on the screen so maybe a little javascript there too. Just thinking out load.

You did a fantastic job!! I have been super tied up with my business so haven't had a real good couple of days off to really attack the Code
  Keep it up I will try to get some of these things added this week.

**Comment by aftechro** [comment]
Hey Johnny!

Glad you like the changes.

For vendors, yes, have to think on the best way to bring them togheter. Maybe joints DB will do the trick.

As for the support type, this is purely for invoicing aspect.
For instance, for maintenance clients who paying monthly fee all incoming phone support, emails or call out jobs are included. Where for non maintenance clients, agent have to charge for the phone support, emails and call outs.
Is this make sense?
Indeed, for some clients we manage just domains, hosting or few things. But they also may call for remote support which will be charged per call.
This is purely based on my experience and would be very handy to have it.

**Comment by aftechro** [comment]
Hi Johnny,

Thanks for implementing the changes, really appreciate it.

Well done with copy to clipboard where i got stuck and couldnt make it work. I suppose, on clinet_logins.php the masked/unmask password still in progress.

If i may few other observation if possible, whenever you get chance...really not urgent

1. For contact phone (all sections) shows the format ___-___-___ which may be the US format, but wont work for other places. Can you please change this to just blank format like +001-__________  as in country code + 10 digits i think most of the countries will have. or even just __________ and allow up to 15 numbers
Couldn't find this from where you can change it, looked at the code and database as vchars but nothing


2. Assigning the ticket to other technician: While you can choose from drop list another user and select the one you need, after saving the ticket changes, not applying. I know there`s a lot to do on the ticketing side, but just to let you to about this issue so far so you can get it sorted now, at the beginning. 


3. Another option but not really a must, it`s more like a personal preferences (which i can code it), is to include into the main sidenav custom urls that will be shown under support menu, so the technician will just click on the link and open a target=blank page of the 3rd party web address that he need to work. This could be done in Settings/Custom urls

like below image

![image](https://user-images.githubusercontent.com/38830718/129024228-2d368b11-3ae8-4e44-ae53-74eb9c260b84.png)

the reason is that, i dont have to code it after each updates :D  Again, not a must, really.

**Comment by johnnyq** [comment]
Hi @aftechro I still really want to get the 2FA OTP working under client logins as well this has proved to be very difficult same with Global Vendors. What I might have is an option to autofill from global vendor. This will autofill the Name, Description, address, city, state, postal code, country  contact, it will leave notes and account number alone and can be filled in as this will be different with clients.

I will also update the phone numbers soon as well

Yes tickets need a lot of love. I will work on the Technician Selection, if you have any ideas and feed back on ticket that will help as well.

External Access Links will be beyond the scope of this project however, what we did for our company is created a start page with links to all the common resources. but let me think of this one because we could make it optional and it would'nt be difficult to code.

**Comment by aftechro** [comment]
Hi Johnny,


YES, OTP is a priority
you could check how the guys from adminer implemented on the login page (which can also be done on itflow)  https://www.adminer.org/en/plugins/otp/  if any help. 

I`m also looking into similar things to see how others done it


For ticketing i have some ideas, but i dont want to give you a head heck. :D 
currently i`m using the OSTickit https://osticket.com/ and done some changes

for instance: 

![image](https://user-images.githubusercontent.com/38830718/129090158-e2c9618f-1e8a-4d59-8a22-1028f8a079ef.png)

this image shows that the person requesting assistance it`s part of the support contract, but also it`s a primary contact, which can request anything, and approve other requests sent to email support


where the below image shows the users is part of suported contract, but needs approval from a primary contact for any requests that involve costs which company needs to pay for
eg. new email account, equipment order, organizing call outs and so on


![image](https://user-images.githubusercontent.com/38830718/129090582-de8e7297-587d-407b-b304-552a66ac6e1f.png)


Also, on that ticket there`s a button to AD to calendar, so this will shows to technician`s calendar (google calendar used) which can easily be tracked for verification purposes (agent`s working aspects)

As you can also see, there`s an INVOICE button, which opens another pop-up windows with invoicing form, where agent can invoice for what ever is related to that ticket. Invoice number is created along with ticket`s reference number  as first line in description section

![image](https://user-images.githubusercontent.com/38830718/129091452-15946ead-b393-426b-b88e-9e8c9fb4f5c2.png)


And last thing, whenever answering a call, a new ticket automatically opens which save the phone number of the caller, and the agent will just fill in the email address and other details for the ticket. 

Using zoiper and custom rule as below
![image](https://user-images.githubusercontent.com/38830718/129092689-840efc53-cf5b-426d-a209-8e8b52461eac.png)


![image](https://user-images.githubusercontent.com/38830718/129092028-fada5035-bd6a-43cb-b6ca-8babfd862565.png)

insert client`s email, which either will show as existing customer, or let you add it as a user
![image](https://user-images.githubusercontent.com/38830718/129092893-0d0a0f0d-2021-4f65-b9fe-75cff342c6d6.png)



will also add the phone number to internal notes, which only support agent will see it
![image](https://user-images.githubusercontent.com/38830718/129092322-e8d3e3ed-0e20-4e77-94de-9af5d4dbb80b.png)


hope this will help you, at least to see what can be done in the future

**Comment by johnnyq** [comment]
OTP has been added cdcd22ae6fb189749654ff05f080352d11eace71

**Comment by aftechro** [comment]
woohoo! Well done Johnny! i`ll have a look later on :D But much appreciated you implemented this

**Comment by aftechro** [comment]
hey Johnny,

we are on the right track, but still work to do.

So i insert the text secret, which generates the code but notice 2 things:

1. the code given not working
2. the otp doesnt refresh

**Comment by johnnyq** [comment]
Hi @aftechro I just noticed this too, TOTP out put code is based off time, i'm wondering if the time is off. For now you have to manually refresh the screen to get the new code it changes every 30 seconds. Try refreshing page and putting in the new code

**Comment by aftechro** [comment]
tried that but not working, it`s like a totally different code. tried with multiple keys, but same thing, does not recognize the code.

**Comment by johnnyq** [comment]
Your right I'm having the same issue, i'm going to have to look more into OTP it could be calculation issue. I'll continue to work on it throughout the week. Ill be pushing a few more updates out today.

Here is the code im using to calculate the 6 digit code

```
function get_otp($secret_seed) {
    //TOTP seed (String representation)
    $otp = '';
    //number of seconds of otp period
    $time_window = 30;

    //time formating to epoch
    $exact_time = microtime(true);
    $rounded_time = floor($exact_time/$time_window);

    //binary represetation of time without padding
    $packed_time = pack("N", $rounded_time);

    //binary representation of time with padding
    $padded_packed_time = str_pad($packed_time,8, chr(0), STR_PAD_LEFT);

    //binary representation of seed
    $packed_secret_seed = pack("H*", $secret_seed);

    //HMAC SHA1 hash (time + seed)
    $hash = hash_hmac ('sha1', $padded_packed_time, $packed_secret_seed, true);

    $offset = ord($hash[19]) & 0xf;
    $otp = (
            ((ord($hash[$offset+0]) & 0x7f) << 24 ) |
            ((ord($hash[$offset+1]) & 0xff) << 16 ) |
            ((ord($hash[$offset+2]) & 0xff) << 8 ) |
            (ord($hash[$offset+3]) & 0xff)
    ) % pow(10, 6); 

    //adding pad to otp, in order to assure a "6" digits
    $otp = str_pad($otp, 6, "0", STR_PAD_LEFT);

    return $otp;
}
```

**Comment by johnnyq** [comment]
@aftechro added custom external links to side nav ef7bfd3c90a5658468a8cfa489551a146616b598
Let me know if this looks good or have any other suggestions for external links

**Comment by aftechro** [comment]
Custom links looking great.

**Comment by johnnyq** [comment]
@aftechro Thank you and now ticket assignment is complete 131e04915b1505ec46bf4a0ea0dcdb7524ab0797

**Comment by aftechro** [comment]
Thank you for this! Amazing and helpful as always!

**Comment by johnnyq** [comment]
>     1. For contact phone (all sections) shows the format   ___ - ___ -___  which may be the US format, but wont work for other places. Can you please change this to just blank format like +001-__________  as in country code + 10 digits i think most of the countries will have. or even just __________ and allow up to 15 numbers

@aftechro This has been done, Basically it you can input phone numbers freely with dashes, pluses () it will just convert them to a number in the backend and then display it properly on output. let me know if it works properly.

**Comment by aftechro** [comment]
Hi Johnny,

good to hear this, i`m away for a week, but i`ll test this and other new stuff on my return.

keep up the great work!
