### ISSUE TITLE
ENHANCEMENT: Link Location and Contact with Client

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#188]
This would make more sense currently the client table has the same fields as the location and contacts table, these can be combined. Lots of code reworking will need to be done

**Comment by iamkhris** [comment]
Here's my 2 cents.  Having to duplicate info creates the problem of when that info changes, you have to change it in multiple places.  I'd like to suggest the following.

On the New Client form, completely get rid of the Contact Tab.

![image](https://user-images.githubusercontent.com/2065198/130376254-3c8d9263-786c-4228-99bb-6c5ce958416b.png)

Then when you've got the Company created, add a new contact, and have some sort of option to flag that contact as the Primary Contact.  Perhaps a checkbox (like in my crude mockup), or whatever is easiest within the framework you're using.

![image](https://user-images.githubusercontent.com/2065198/130376308-52ff1de2-4619-4174-807d-3570e1da7553.png)

Then, when you've selected the primary contact, it will be displayed here, and anywhere else a Primary Company contact could be referenced.

![image](https://user-images.githubusercontent.com/2065198/130376333-33a6affb-1890-4a66-b303-d48ee0c6539c.png)

It could even go another step further and have Primary, Technical, Billing contacts which you would flag from the list of available company contacts.  Then when you go to send an invoice, it automatically goes to the Billing contact, etc.

**Comment by johnnyq** [comment]
Fantastic @iamkhris I will be implementing this and it makes so much sense. Although this update is going to have some breaking changes but we need to do this to move forward. I also love the idea of a billing and technical contact. We will do the same for locations and have it choose a primary location

**Comment by iamkhris** [comment]
@johnnyq Awesome.  Yes, love the primary location idea as well!  Sometimes each location has their own primary/billing/technical contact too so something else to consider.

The other similar issue I noticed was with Vendors.  You can create a Vendor in the root of ITFlow, and then you can create additional Vendors for each client.  It would be nice if it were possible to have two lists, a Global Vendors list which are entered at the top level, and then a separate list which are unique to the clients.  This again saves from duplicating information and having multiple places to update if there is a change.  (I can create a separate issue for this if it's helpful)

**Comment by johnnyq** [comment]
Major breaking changes went into place to make this happen which will allow us to do some amazing things in the future, this code refactoring was long overdue.

f3053ffbd44b0310f4d7626e823f225bc10a3371

**Comment by johnnyq** [comment]
Closing as this is now complete
