### ISSUE TITLE
ENHANCEMENT - Client Screen Layout

### ISSUE THREAD

**Issue by iamkhris** [johnnyq/itflow#189]
When I look at this screen, my eyes get a bit confused as to where to click to get the client/info I'm looking for.  I'd like to propose a couple visual 
![Option1](https://user-images.githubusercontent.com/2065198/130340532-29bb11b0-6e1c-47ab-a021-84ad3da97b08.png)
![Option2](https://user-images.githubusercontent.com/2065198/130340533-3321863c-c2ae-43b0-94b7-172fb9d3a882.png)
options.

**Comment by aftechro** [comment]
I do like the new design and the way the info is presented. Your proposed changes, means that longer line text if client really having a long name + Support type on the same line. Not ideal

I  like how the client section is presented atm, everything on separate lines (clear and easy to read the info)
1. client name
2. client type
3. support type
4. contract details

What i suggest if i may, is that when you hover/click on the entire client block, to open the client`s page, so in that case it`s easier for everyone to access the client, instead on clicking on the client`s name (which can be confusing for some)

**Comment by iamkhris** [comment]
I didn't consider the length of the client name, and then adding on a support string after it. I think it's the space underneath the client name, before the Support and Contract details that is throwing my eyes off.  This makes more sense to me personally.

![image](https://user-images.githubusercontent.com/2065198/130361005-4037277f-6c8e-421a-95e1-3f3f8dda77d9.png)

 As another alternative, perhaps a green or red solid icon in front of the client name indicating whether they're managed or not.  It's unobtrusive, yet 100% indicative of support state.

![image](https://user-images.githubusercontent.com/2065198/130361024-efbc05f4-d950-4aa6-bc9f-6d389d8cbf85.png)

**Comment by johnnyq** [comment]
@iamkhris I like the colored support contract icon next to the client name Im wondering if also bolding the Client Name to make it easier when clicking. Ill go ahead and implement.

**Comment by iamkhris** [comment]
@johnnyq  Do you mean bolding the client name for all entries (and then support contract info underneath would be regular), or only bold those with a valid support contract?

**Comment by johnnyq** [comment]
@johnnyq Bolding all client names and using the support contract icon in front of the name as you have it. Bolding the Client name will help define it as a clickable entry. I also like what @aftechro said to make the entire link clickable, although it may cause issues with the Bootstrap CSS Framework that i'm using. What do you think would bolding the name be a good idea?

**Comment by iamkhris** [comment]
@johnnyq Without seeing it I can’t say for sure, but I also don’t see any real issues with it.  I agree that it makes it stand out and identifiable as a clickable item whereas other items not bolded would be for informational purposes only.  Sounds like a reasonable idea to me. :)

**Comment by johnnyq** [comment]
@iamkhris @aftechro Okay UI changes have been made to client listing let me know if you guys like it or if anything should be changed. Thanks

**Comment by iamkhris** [comment]
@johnnyq Love it!!  Thank you :)  I think it looks fantastic.

**Comment by johnnyq** [comment]
@iamkhris Execllent Thank you Ill close this out for now Thanks for reporting =]

**Comment by aftechro** [comment]
That`s look great! I was bit concerned that the staff wont know if client maintenance or not just by the color of the icon, but as long while inside the client page, on the top under company name, it`s also the full text of the support state, that`s great :d
