### ISSUE TITLE
Bug: Email test/config

### ISSUE THREAD

**Issue by aftechro** [johnnyq/itflow#195]
Hey Johnny,

I`m trying to set my SMTP as Office365 one, but for some reason not working.

I`m able to input SMTP details and save the section, but when i test the email or when i actually trying to send a test invoice, not working 

Can there will be option to either user SMTP or phpmailer from the hosting system

**Comment by RVL-Solutions** [comment]
Can you confirm that SMTP is allowed for the mailbox within your O365 tenant?

**Comment by aftechro** [comment]
SMTP enabled, below error


    2021/09/26 22:55:37 [error] 338812#338812: *357 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: 
    company_currency in /home/itflow/public_html/check_login.php on line 48" while reading response header from upstream, 
    client: 1.2.3.4, server: domain.tld, request: "GET /settings-mail.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:8007", host: 
    "domain.tld", referrer: "https://domain.tld/settings-general.php"
    2021/09/26 22:55:39 [error] 338812#338812: *357 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: 
    company_currency in /home/itflow/public_html/check_login.php on line 48" while reading response header from upstream, 
    client: 1.2.3.4, server: domain.tld, request: "POST /post.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:8007", host: "domain.tld", 
    referrer: "https://domain.tld/settings-mail.php"
    2021/09/26 22:55:39 [error] 338812#338812: *357 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: 
    company_currency in /home/itflow/public_html/check_login.php on line 48" while reading response header from upstream, 
    client: 1.2.3.4, server: domain.tld, request: "GET /settings-mail.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:8007", host: 
    "domain.tld", referrer: "https://domain.tld/settings-mail.php"
    2021/09/26 22:55:39 [error] 338812#338812: *357 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: 
    alert_type in /home/itflow/public_html/header.php on line 67" while reading upstream, client: 1.2.3.4, server: domain.tld, 
    request: "GET /settings-mail.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:8007", host: "domain.tld", referrer: 
    "https://domain.tld/settings-mail.php"
    2021/09/26 22:56:58 [error] 344218#344218: *1 FastCGI sent in stderr: "PHP Notice:  Undefined index: logged in 
    /home/itflow/public_html/check_login.php on line 11" while reading response header from upstream, client: 208.115.199.21, 
    server: domain.tld, request: "HEAD / HTTP/1.1", upstream: "fastcgi://unix:/var/php-nginx/16325192814677.sock/socket:", host: 
    "domain.tld", referrer: "https://domain.tld"
    2021/09/26 22:57:13 [error] 344218#344218: *7 FastCGI sent in stderr: "PHP Notice:  Undefined index: company_currency in 
    /home/itflow/public_html/check_login.php on line 48" while reading response header from upstream, client: 1.2.3.4, server: 
    domain.tld, request: "GET /settings-mail.php HTTP/1.1", upstream: "fastcgi://unix:/var/php- 
    nginx/16325192814677.sock/socket:", host: "domain.tld", referrer: "https://domain.tld/settings-mail.php"
    2021/09/26 22:57:16 [error] 344218#344218: *7 FastCGI sent in stderr: "PHP Notice:  Undefined index: company_currency in 
    /home/itflow/public_html/check_login.php on line 48" while reading response header from upstream, client: 1.2.3.4, server: 
    domain.tld, request: "POST /post.php HTTP/1.1", upstream: "fastcgi://unix:/var/php-nginx/16325192814677.sock/socket:", 
    host: "domain.tld", referrer: "https://domain.tld/settings-mail.php"
    2021/09/26 22:57:16 [error] 344218#344218: *7 FastCGI sent in stderr: "PHP Notice:  Undefined index: company_currency in 
    /home/itflow/public_html/check_login.php on line 48" while reading response header from upstream, client: 1.2.3.4, server: 
    domain.tld, request: "GET /settings-mail.php HTTP/1.1", upstream: "fastcgi://unix:/var/php- 
    nginx/16325192814677.sock/socket:", host: "domain.tld", referrer: "https://domain.tld/settings-mail.php"
    2021/09/26 22:57:16 [error] 344218#344218: *7 FastCGI sent in stderr: "PHP Notice:  Undefined index: alert_type in 
    /home/itflow/public_html/header.php on line 67" while reading upstream, client: 1.2.3.4, server: domain.tld, request: "GET 
    /settings-mail.php HTTP/1.1", upstream: "fastcgi://unix:/var/php-nginx/16325192814677.sock/socket:", host: "domain.tld", 
    referrer: "https://domain.tld/settings-mail.php"
    2021/09/26 22:57:42 [error] 344218#344218: *7 FastCGI sent in stderr: "PHP Notice:  Undefined index: company_currency in 
    /home/itflow/public_html/check_login.php on line 48
    PHP Notice:  Undefined variable: mail@domain.tld in /home/itflow/public_html/post.php on line 636
    PHP Fatal error:  Uncaught Error: Class 'PHPMailer\PHPMailer\Exception' not found in 
    /home/itflow/public_html/vendor/PHPMailer-6.5.1/src/PHPMailer.php:2159
    Stack trace:
    #0 /home/itflow/public_html/vendor/PHPMailer-6.5.1/src/PHPMailer.php(1970): PHPMailer\PHPMailer\PHPMailer- 
    >smtpConnect()
    #1 /home/itflow/public_html/vendor/PHPMailer-6.5.1/src/PHPMailer.php(1648): PHPMailer\PHPMailer\PHPMailer- 
    >smtpSend()
    #2 /home/itflow/public_html/vendor/PHPMailer-6.5.1/src/PHPMailer.php(1486): PHPMailer\PHPMailer\PHPMailer- 
    >postSend()
    #3 /home/itflow/public_html/post.php(639): PHPMailer\PHPMailer\PHPMailer->send()
    #4 {main}
    thrown in /home/itflow/public_html/vendor/PHPMailer-6.5.1/src/PHPMailer.php on line 2159" while reading response header 
    from upstream, client: 1.2.3.4, server: domain.tld, request: "POST /post.php HTTP/1.1", upstream: "fastcgi://unix:/var/php- 
    nginx/16325192814677.sock/socket:", host: "domain.tld", referrer: "https://domain.tld/settings-mail.php"

**Comment by aftechro** [comment]
Hey guys,

Sorted by using app password in Office365.

@johnnyq can we add a filed in the email settings "Display send as" where we can add display name of the email sender?

Thank you!

**Comment by johnnyq** [comment]
Hi @aftechro im glad the app password worked for you, that would be something i'll add to documentation for the future.

The Display Send as is actually the name field in Setting > General > Mail update that field and it will produce what you want.

I may update the field to be a little more descriptive I like "Display Send as"

**Comment by aftechro** [comment]
Hey @johnnyq 

Yes, i did the Name filed, and found also the issue for that on my end :D looks like the email address used, was saved under contact address book under different name, and when email received, showed that name

I`ll send you an email to request access to documentation so i can add as i discover things :D
