### ISSUE TITLE
Feature: More Country and State Choices

### ISSUE THREAD

**Issue by Panchalhariom07** [johnnyq/itflow#199]
Hey,
Can you please tell me how to add new location ( Country State and City ) ?

**Comment by johnnyq** [comment]
Hi @Panchalhariom07 Create a client or click on an existing client under client listing. Click Locations on the Client Side Nav menu then choose new location. Fill out the info and that should do it. This allow you to add another location for a client.

**Comment by johnnyq** [comment]
@Panchalhariom07 I see what your saying. The State and Country is currently staticly embedded in the code and is not programmed in. Im going to have to update the code to include all countries and states within the country. For Example if you selected India for country then the state select list will only show states in India same for Canada and USA etc. I'll see if I can find some code online that would work nicely with this. Ill keep you posted. In the meantime if you really want to add additoonal states and countries you can modify the file get_settings.php you will find the states and country array and add additional ones in the time being.

**Comment by johnnyq** [comment]
Okay after doing some research I think the best thing to do is make state a text input instead of a select, and leave country as select but introduce all countries, ill get this fixed up before the end of the week

**Comment by johnnyq** [comment]
Complete 72cf61ab61c3b91324ea71b9795cf978abdf6ff0
Also added all the countries and states are now text fields
