### ISSUE TITLE
New clients not showing up

### ISSUE THREAD

**Issue by DarkObscurity** [johnnyq/itflow#200]
Hey!

I reinstalled ITFlow a few times now, but for some reason when I add clients, they do not show up.
I checked the database and they are listed in the database with the correct information, but I can't seem to get them to show up in the web interface.

Am I maybe missing something?

**Comment by DarkObscurity** [comment]
I read through some other issues and found one saying records weren't correctly displayed when using MySQL, so I installed MariaDB and now everything seems to work..

Maybe it's an idea to mention this in the installation section? :)

**Comment by johnnyq** [comment]
Good call will do @DarkObscurity
