### ISSUE TITLE
Feauture request: Expenses - description

### ISSUE THREAD

**Issue by aftechro** [johnnyq/itflow#203]
Hi @johnnyq,

Hope you are well!

Was just adding the expenses, and looking at it, i feel like missing something.

For instance: on the /expenses.php can you also add a description of the expense so that would be easy to find it without being needed to click on it, for a faster check.

For instance, lets say i have same vendors but with different expenses. ATM, it`s only showing: vendor and category

![image](https://user-images.githubusercontent.com/38830718/142504549-d4dbaea0-674a-4677-8240-0e1d4940b415.png)

can we add the description filed in that table, so would be way much easier to know exactly from the same vendor for the same category, what exactly the expense is for.

| amount | vendor | description | category |
| -------- | -------- | ------------- | ---------- |
| 50 | vendor x | account setup client A | webhosting |
| 50 | vendor x | account setup client B | webhosting |
| 50 | vendor x | increase disk size | webhosting |
| 50 | vendor x | backup | webhosting |
| 50 | vendor Z | renewal | domain |
| 50 |  vendor Z | transfer | domain |

unlike 

| amount | vendor | category |
| -------- | -------- | ---------- |
| 50 | vendor x | webhosting |
| 50 | vendor x | webhosting |
| 50 | vendor x | webhosting |
| 50 | vendor x | webhosting |
| 50 | vendor Z | domain |
| 50 |  vendor Z | domain |

what you think? Is just that will be much faster, especially if you are setting similar expenses from same vendors and categories.

Thank you in advance!

**Comment by johnnyq** [comment]
I agree! Currently I already have a description box but sometimes the text can be too big if their are multiple items on one expense. I think what will work is adding a Short Description field or maybe using the description field but truncating the current description to 50 characters to display nicely in list view. I'm leaning more towards a separate field for this though, what are your thoughts?

**Comment by aftechro** [comment]
i`m for the truncating the description to whatever number of characters the table permits 30-50.

or even better if not to much to ask, dont wanna push it :d 
truncated description with preview of full description on mouse hover

**Comment by johnnyq** [comment]
Nice! I like that idea, working on it as I type

**Comment by aftechro** [comment]
Great! :D 

I`ll let you clear down as much as you can, before putting there other feature requests :D

**Comment by johnnyq** [comment]
Done! little easy detail things like this are nice. They make for a nice Quality of Life improvement. Keep up with the suggestions =]

**Comment by aftechro** [comment]
Yep, that works just fine. Now it`s easier for both myself and accounting person to find what needed. 
Thank you!
