### ISSUE TITLE
Integrations / api documentation

### ISSUE THREAD

**Issue by obsjmartin** [johnnyq/itflow#205]
Nice project. I really like what I see so far. One of the biggest selling points of itglue was the ability to import client records from connectwise or autotask. I realize this is a tall task for an open source project that's just gotten off the ground. Does the api allow for record creation? 

Another api question. Can the api allow for user accounts to added and removed from groups? I'm thinking of  privileged identity management in azure ad that could add and remove user accounts from access.groupa via power automate. 

Another wishlist item would be azure ad / Google single sign on.

**Comment by johnnyq** [comment]
@obsjmartin Thank you for your interest in this project, im glad it can be of use. The API is very limited at the moment and does not have the functions you describe. Also we do not support Google/Azure AD OAUTH2 support at the moment and may not right away until maybe OAUTH2.1 /3.0 comes out. There's a few privacy and security concerns surrounding the protocol at the moment along with some technical hurdles.

**Comment by johnnyq** [comment]
closing this issue for now, we may implement it further down the road but must crunch out the high priority things first.
