### ISSUE TITLE
No Clients?

### ISSUE THREAD

**Issue by Nate-09** [johnnyq/itflow#206]
Hi Everyone,

I appear to be experiencing some issues with the clients in a fresh install on the latest project.

I've created three clients so far and all of the show in the Dashboard as seen below:
![image](https://user-images.githubusercontent.com/87747569/143956027-cc82cabf-626a-4611-bd35-10aa53a3f71a.png)

However when I attempt open a client I get a Records? whattt error
![image](https://user-images.githubusercontent.com/87747569/143956084-ee005efb-47cc-4ffc-840e-2eadfebb4770.png)

I'm running on Ubuntu 20.04 on an LEMP stack - not sure why or where this is going wrong, followed the guide on the wiki page and itflow/docs.

**Comment by johnnyq** [comment]
Are you using MySQL or MariaDB as your database?
Currently ITFlow has an issue with MySQL.

**Comment by johnnyq** [comment]
Are you using MySQL or MariaDB as your database?
Currently ITFlow has an issue with MySQL.

**Comment by Nate-09** [comment]
> @Nate-09 Are you using MySQL or MariaDB as your database? Currently ITFlow has an issue with MySQL.

Currently using MySQL.

So I'd be better off removing the web data and SQL and install MariaDB and re-run setup?

**Comment by Nate-09** [comment]
> @Nate-09 Are you using MySQL or MariaDB as your database? Currently ITFlow has an issue with MySQL.

Hi @johnnyq Thanks for that, I was using MySQL, I've removed it and reinstalled with MariaDB and it works perfectly now.
