### ISSUE TITLE
Unable to Modify Assets after Update:

### ISSUE THREAD

**Issue by ThatsNASt** [johnnyq/itflow#209]
I have updated to c88e6b851aadfbde173f7cfe7155dd1ed31adece and after I am unable to modify an asset that I already have in the system. I can add a field and save it, but it doesn't actually show up as changed. Log shows I've changed an asset, though.

**Comment by johnnyq** [comment]
I think i fixed this go ahead and update again, this is due to the new sql field install_date that was added to assets. The new update should add the appropriate field to the DB
