### ISSUE TITLE
Passwords containing " character do not save correctly

### ISSUE THREAD

**Issue by adamjrberry** [johnnyq/itflow#210]
Test password: Sr)vt2"}z6HtKcya

When saving this test password, it returns:
![image](https://user-images.githubusercontent.com/63184938/145437071-1e0a28c3-9a88-4a23-bddb-233ce46aeeb1.png)

When I remove the speech marks ", the password saves correctly.

**Comment by johnnyq** [comment]
I think i fixed this go ahead and update again, this is due to the new sql field install_date that was added to assets. The new update should add the appropriate field to the DB

**Comment by johnnyq** [comment]
Thanks for reporting. Im on it

**Comment by johnnyq** [comment]
Hi @adamjrberry They were being save correctly in the DB however certain HTML characters were not escaped under output. This should be fixed Thanks for the the report.

**Comment by adamjrberry** [comment]
Thank you very much! Yes it now works after updating :)
