### ISSUE TITLE
Cannot complete setup, just goes back to start.

### ISSUE THREAD

**Issue by mkono87** [johnnyq/itflow#211]
I cannot seemed to get back the setup. I have tried connecting to my remote mariadb instance on the same LAN and created on locally. Once entering all the information and submit it, it just goes back to the setup page where I started.

On a side note, your DEMO is asking for OTP. How can one get into that??

**Comment by johnnyq** [comment]
Hi @mkono87 We were doing some work on the code you may have cloned the code earlier try again, we just installed it on a HestiaCP platform with Apache and MariaDB a half hour ago.

The Demo site is working again, 2FA was set

**Comment by mkono87** [comment]
> Hi @mkono87 We were doing some work on the code you may have cloned the code earlier try again, we just installed it on a HestiaCP platform with Apache and MariaDB a half hour ago.
> 
> The Demo site is working again, 2FA was set
> 
> 

Much appreciated thanks!

**Comment by mkono87** [comment]
Just cloned the repo again and tried setting it up but im facing the same issue of it going back to the beginning. Also tried local and remote mariadb, not sure if thats the issue but shouldn't be.

**Comment by johnnyq** [comment]
Im not sure if you done this. You will want to create the database and database user along with the password using phpmyadmin or using mysql commands and then run setup. Also anything in the apache errors logs?

**Comment by mkono87** [comment]
> Im not sure if you done this. You will want to create the database and database user along with the password using phpmyadmin or using mysql commands and then run setup. Also anything in the apache errors logs?

phpmyadmin is exactly what I used. Just want to make sure, does it want http://   or just ip:3306?

Il check the errors again when I get a chance.

**Comment by mkono87** [comment]
@johnnyq Here is a bunch from the logs. Maybe you can point something out.

https://pastebin.com/vKEp4222

**Comment by johnnyq** [comment]
@mkono87 It looks like config.php is missing and not being created. I bet this is a permission issue.

Make sure the the directory owner has read write permission over the files

usually www-data

so if your itflow files are in /var/www

do a chown -R www-data:www-data /var/www

**Comment by johnnyq** [comment]
Hi @mkono87 did you have any luck?

**Comment by mkono87** [comment]
> Hi @mkono87 did you have any luck?

Have not had a chance yet but will tomorrow. Il report back.

**Comment by mkono87** [comment]
@johnnyq Yes that seemed to work thanks!

Another question if you dont mind instead of creating another issue. Is it possible at all to change the listen address? The system id have it on has a reverse proxy in front so this cannot use 80. Only other solution would be convert this in to a docker container so I can pass another host port.

**Comment by DarkObscurity** [comment]
> @johnnyq Yes that seemed to work thanks!
> 
> Another question if you dont mind instead of creating another issue. Is it possible at all to change the listen address? The system id have it on has a reverse proxy in front so this cannot use 80. Only other solution would be convert this in to a docker container so I can pass another host port.

The listening address/port is determined by the software you're using to host the website like Apache.
On what kind of software/environment are you running? And as well, if you're using a reverse proxy you should be able to pass through the connection to a different machine that is listening to port 80, you'd only run into problems when you're running the reverse proxy on the same machine as you're going to host IT-Flow and you're using different packages to host the sites, like for example Nginx for the reverse proxy and Apache 2 for IT-Flow, then it's not possible to have both packages listening to the same IP+port combination. If you'd have multiple IP addresses assigned to the host you could also give each package their own IP address to listen to.

I also use a reverse proxy for all my web traffic and IT-Flow is just running inside a different VM and listening on port 80.

**Comment by johnnyq** [comment]
@mkono87 I belive this is fixed now please try and report back @mkono87

**Comment by mkono87** [comment]
> @mkono87 I belive this is fixed now please try and report back @mkono87

What are you referring to, the listen port?

**Comment by johnnyq** [comment]
"Cannot complete setup, just goes back to start"

**Comment by mkono87** [comment]
> "Cannot complete setup, just goes back to start"

Oh I already told you the setup now works, thats why I was confused. https://github.com/johnnyq/itflow/issues/211#issuecomment-992688313

**Comment by johnnyq** [comment]
lol it would help if I read that Thanks @mkono87 Ill close this out
