### ISSUE TITLE
InvoiceNinja Integration

### ISSUE THREAD

**Issue by LefflerMediaLLC** [johnnyq/itflow#212]
This would be awesome if I could import invoices/etc from InvoiceNinja

**Comment by johnnyq** [comment]
@LefflerMediaLLC 

That should be possible, I used an app called akaunting before ITFlow and was able to import that data using SQL row matching to ITFlow. It took some time but it worked out.

Are you planning on using InvoiceNinja with ITFlow or just switch to ITFlow fully

**Comment by johnnyq** [comment]
@LefflerMediaLLC Goign to close this for now as this is possible with SQL column matching
