### ISSUE TITLE
Keep Getting An Error When Setting Up

### ISSUE THREAD

**Issue by athornfam2** [johnnyq/itflow#213]
https://github.com/johnnyq/dvis/blob/main/itflowcrminstall.sh used the script here and now at the end after adding the user, user password, and database name I get an error database connection failed.

**Comment by johnnyq** [comment]
Hi @athornfam2 go into the folder /var/www/YOURDOMAIN and rm the config.php
start over and put in itflow for username and itflow for database In all lower case
The info at the end of the script is incorrect and tells you to enter ITFlow I will fix this.

**Comment by athornfam2** [comment]
Ok. I got past that where it at least shows the page... but I got my information in a string that goes across the login page...

What's the default login information for a new build?

**Comment by johnnyq** [comment]
Hi @athornfam2 send me some apache2 logs ill take alook

**Comment by athornfam2** [comment]
[access.log](https://github.com/johnnyq/itflow/files/7715600/access.log)
[error.log](https://github.com/johnnyq/itflow/files/7715601/error.log)

These are the only apache log files I have and they don't have much in them from what I could see.

**Comment by johnnyq** [comment]
Hi @athornfam2 Sorry I missed this post. I fixed the issue that was causing the setup script to get hung up. Give it another Whirl but don't use the install script as that needs rewritten follow the installation instructions in the readme.

**Comment by johnnyq** [comment]
@athornfam2 Any luck?

**Comment by athornfam2** [comment]
I haven’t had a chance to look at it. I’ll see what I can do tonight or tomorrow.

**Comment by athornfam2** [comment]
Everything is working now.

Also, the script does work. Not sure how to make a contribution to the script but here's what I changed and tested below on 20.04 LTS

`sudo apt-get install -y mysql-server`
`sudo mysql_secure_installation`

to

`sudo apt-get install -y mariadb-server`
`sudo mariadb_secure_installation`

**Comment by johnnyq** [comment]
Fantastic I will get that added Thanks for the update

**Comment by johnnyq** [comment]
Okay I updated the script to include the changes, I made a few others as well.
