### ISSUE TITLE
Taxes with decimal %

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#216]
Hi,

In the taxes fields, we're not able to use decimals number. In the area where I'm living, one of the taxes a 9.975%.

There is a warning telling me: "Please enter a valid value. The two nearest valid values are 9 and 10."

Where I can modify this behavior?

Regards,

**Comment by johnnyq** [comment]
Hi @Wikiphil Currently not possible, ill work on an update this week that resolves this.

**Comment by johnnyq** [comment]
Fixed go ahead and update @Wikiphil

**Comment by Wikiphil** [comment]
It Works! 

Is there a way to merge multiple taxes? 

As an example, in Canada, most of the provinces have 2 seperate taxes, we have to show them both on all invoices.

**Comment by johnnyq** [comment]
Nice,

hmmm good question and I did not know that I guess we could add a column called tax2.

I think the best approach to this is see how other Invoicing software handles this ex invoiceplane, akaunting, craterapp

**Comment by Wikiphil** [comment]
Instead of calculate tax on each items, we can calculate it on the bottom only. Most of the software do it that way.

Example:

1 x item #1      cost each 1.00$      1.00$
2 x item #2      cost each 1.00$      2.00$
10 x item #3      cost each 1.00$    10.00$

Subtotal            13.00$
Tax #1 - 5%         0.65$
Tax #2 9.975%     1.30$
Total with taxes  14.95$

**Comment by johnnyq** [comment]
@Wikiphil Good idea we will take that approach. Register with our forum we just set it up today, hoping to drive some community there. https://forum.itflow.org
