### ISSUE TITLE
Tax rate issues with 0.5%

### ISSUE THREAD

**Issue by HollowCyberSec** [johnnyq/itflow#217]
The tax rate can only be set to whole numbers. In my case, our tax rate is 11.5 and cannot be set up.

**Comment by johnnyq** [comment]
Hi @HollowCyberSec This was recently fixed with commit f2763476a34dce7fc21008817923209df7344c96
Once updated it should work

**Comment by HollowCyberSec** [comment]
Tested! Thanks, works like a charm!
