### ISSUE TITLE
Certain db passwords don't work

### ISSUE THREAD

**Issue by calculatetech** [johnnyq/itflow#219]
I'm installing ITFlow on a Synology with MariaDB 10 and struggled getting the database configured.  Turns out the password I generated doesn't get parsed correctly somewhere.  The password was ??36$certain$TORE$should$86??.

**Comment by johnnyq** [comment]
@calculatetech I can replicate I think the $ is causing the issues its mimicking a php var ill work on this

**Comment by johnnyq** [comment]
Hi @calculatetech an anonymous person submitted a fix for this issue, go ahead and give it a shot and let me know if its working for you now

cf3c0a64106ea27ac432d8bba4826b5f1b7b881e

**Comment by johnnyq** [comment]
This is fixed closing this Thanks
