### ISSUE TITLE
Bug: Import Function

### ISSUE THREAD

**Issue by athornfam2** [johnnyq/itflow#220]
The import function under customer assets does not work. Export does work though.

Troubleshooting:

* Tried Firefox
* Tried IE11
* Tried from my RDS farm and workstation
* Attempts were done only locally as the system is not accesible outside the LAN

**Comment by johnnyq** [comment]
@athornfam2 Your right its there for show right now, still haven't implemented that function. Ill keep this open until then

**Comment by wrongecho** [comment]
@athornfam2 I've added basic functionality for this in #248, with basic API asset import functionality in #249.
