### ISSUE TITLE
Feature Request: Time Entry

### ISSUE THREAD

**Issue by athornfam2** [johnnyq/itflow#221]
Would like to request a feature. A popular feature I would use in CW was to track time based on ticket entry at the comment or sent response. When I went to go in to make a ticket and then track the time I didn't see that function unless its hidden in the system settings.

Feature Request: Add a time based entry system at the ticket level.

**Comment by johnnyq** [comment]
good idea! that would make a great additon, ill try to get this added very soon.

**Comment by aftechro** [comment]
That`s a tricky one, as we all know there are times when you can answer right away with a solution, or you may need to do a research in getting and trying different solutions. 

The way i work, probably like many others... i dont count the time spent on replying to a ticket instead i`m using this system:
- for maintenance clients - support is included, no time to record
- for non-maintenance - there will be a minimum charge of 0.30 minutes for any type of work (email, phone, remote) - so even though the call is 5 minutes, or remote task is 10 minutes, i`ll still charge 30 minutes for it. Over 30 minutes, i`ll apply the hour rate and so on...in the end, i`m only charging for the actual task itself

But of course, i`ll always do that with common sense - i wont charge if i`m just replying or sharing some knowledge over the phone or email

What i will like to have on the ticketing system. are few buttons: 
-  **add to calendar** - either itflow calendar or integrate with google - (maybe close/resolve ticket and add to callendar) 
-  **invoice** - to open the new invoice - and the subject to start with ticket number eg: #2343 Printer not working - so the invoice reflect the ticket which can be verified on both sides (MSP and customer)

example as i`ve changed it on the osticketing
![image](https://user-images.githubusercontent.com/38830718/147582129-1d221359-01f2-499c-b11d-a4966e53f113.png)

**Comment by athornfam2** [comment]
@aftechro I think my request was more to just have a time entry in general as each MSP and tech (I used a tech SysAdmin) has different formula's to their work. I wouldn't want any entry's to be fixed (ex .25 .50 .75)... Like you said that phone call only may be 3 to 5 minutes... So I still want a time entry but make it a NB (non-billable charge) but still counts towards tech time and as a response.

The thinking in this is similar to how CW Manage works.

**Comment by wrongecho** [comment]
I too like the idea of the timer that just counts up as you work, but you can edit it.
Similar to this: https://docs.servicenow.com/bundle/rome-platform-administration/page/administer/time/image/TimeTimeworked.png

**Comment by wrongecho** [comment]
Hi both, I've submitted a pull for this. I've gone for the accurate time-tracking approach. I guess if you want to bill on the time, we can add it up and round it in the calendar and then/or report/billing?

**Comment by athornfam2** [comment]
@wrongecho If it was either added to the repo or on the list to add to 1.0 it's fine to close.
