### ISSUE TITLE
Bug: Ticketing Bad Request 

### ISSUE THREAD

**Issue by athornfam2** [johnnyq/itflow#224]
Getting an error when click on the following buttons below.

![2021-12-28 13_55_24-Window](https://user-images.githubusercontent.com/74559383/147598010-79515b27-3547-4d28-af76-71c4d99ab4bd.png)

![2021-12-28 13_45_02-Window](https://user-images.githubusercontent.com/74559383/147597977-45617e5c-71d9-4982-9390-d620933f1d6d.png)

**Comment by aftechro** [comment]
getting the same, let`s keep an eye on this and hope Johnny will have time to look at this, as i know he`s quite busy on many other tasks
