### ISSUE TITLE
Mail Settings Error

### ISSUE THREAD

**Issue by HollowCyberSec** [johnnyq/itflow#226]
Added mail settings, when testing email page keeps attempting to load but never does. If you try to change tabs or refresh the page it doesn't do anything. You have to close it down, clear the cache, and log in again.

**Comment by aftechro** [comment]
Not sure if this a local issue on your end, but try to download latest version and follow the instructions from DOCS section
Have a look here: https://itflow.org/docs.php?doc_id=2 

everything up and running for my live versions as well on my dev version (which pulls all the new changes)

**Comment by johnnyq** [comment]
Any Luck? Who are you using for a mail provider @HollowCyberSec

**Comment by johnnyq** [comment]
closing was not able to replicate
