### ISSUE TITLE
Ticket Details is vulnerable to XSS

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#232]
The ticket details & ticket replies are vulnerable to cross-site scripting.

To replicate, open a new ticket with the description `<script> alert(1) </script>`

Normally this is easily fixed with strip_tags/htmlentities, however as part of summernote we probably want to allow some HTML formatting right?

They have a discussion open regarding this, but their perspective generally seems to be that it's the app's responsibility to sanitize input/output.
https://github.com/summernote/summernote/issues/3719
https://github.com/summernote/summernote/pull/3782

Edit: worth mentioning 'Documents' function is also vulnerable, as it uses summernote as well.

**Comment by DiemenDesign** [comment]
We are open to changes to have the Summernote API sanitise input/output, even though the App should also be santizing data. For contributions and discussion, please refer to https://github.com/summernote/summernote/pull/3782 
Current solutions that have been tested, end up muxing the html markup, obviously this isn't desired.

**Comment by johnnyq** [comment]
@wrongecho Your right i didn't know a good approach to attack this issue and just warded it off as user that have an access are assumed trusted, but if we allow external public input this indeed would be a serious issue.

**Comment by DiemenDesign** [comment]
@johnnyq The Summernote project are open to workable solutions that will benefit all users. So far we haven't been able to come up with a working solution (apart from sanitation outside of the Summernote API) that doesn't break html formatting.

**Comment by johnnyq** [comment]
@DiemenDesign I think your right and it should be done at the backend layer I just have to figure out the best approach using Plain old PHP with no framework

**Comment by DiemenDesign** [comment]
I use HTMLPurifier in my project, it's not huge, it's fast, and simply works. I too spent a lot of time trying to work out a solution, and found HTMLPurifier and figured why reinvent the wheel.

**Comment by wrongecho** [comment]
Thank you for the suggestion, @DiemenDesign.
I've had a go with the demo at http://htmlpurifier.org/demo.php?post in conjunction with https://portswigger.net/web-security/cross-site-scripting/cheat-sheet and this seems to do the trick nicely.
