### ISSUE TITLE
Asset login encryption thoughts

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#264]
Just some thoughts on how ITFlow is handling the encryption of asset/login passwords (not like login to the app itself).

**No salt when encrypting passwords**
If you encrypt two login entries with the same password, you get the same output. Presumably, this is due to no salt/IV. 
We should probably be salting passwords?

**Storing AES key in database**
Currently, we're storing the AES encryption key in the database. Theoretically, if an attacker were to gain access and dump the database, they have the key they need to decrypt all passwords.

I've done a little research and the general consensus seems to be to use a HSM (which probably isn't an option for a lot of us). 
Other than using a HSM, there are a few options. There's a good answer here: https://security.stackexchange.com/questions/12332/where-to-store-a-server-side-encryption-key/12334#12334

One way of countering this may be to encrypt the AES key with a shared passphrase (that you communicate to your IT team) and then prompt for this phrase when you want to decrypt a password. 
This passphrase is potentially then stored in the session/DB/apc(?) so the user isn't constantly prompted for it to see every entry - as long as it is destroyed after the user's session ends. This isn't perfect either (as the key is still plain text at some point - security vs usability here) but substantially reduces the attack surface?

Alternatively, if we don't want to make users have to remember a shared secret, we could encrypt the AES key for each user individually with their account password and decrypt it at login. This is slightly more usable but then requires users to have really good passwords. Still the question of whether to store the shared passphrase or prompt for their password every time to decrypt it.

I think at the very least we should move the AES key out of the database & into a file. At least then you'd need to compromise the server and the database to decrypt passwords.

Keen to hear opinions on both of these, please?

**Comment by johnnyq** [comment]
I know the AES key being stored in the database is definitely not the best of ideas. I like option 2 where we encrypt the AES key for each user. All users should be using good passwords anyway. I believe this is how big password managers like Bitwarden do it.

**Comment by wrongecho** [comment]
#265 resolves this issue.
As a summary:
- At setup, a "master" AES key is generated and is encrypted with the initial user's password. This is done using PBKDF2 and a salt to generate a 128-bit key. AES-128-CBC (+ IV) is then used to generate the encrypted password. This is the "user specific key".
- Upon login, the user's password is used to decrypt their Specific Key in order to retrieve the master key. 
- In order for the master key to never be left in a non-encrypted format anywhere, we then encrypt the master key (with the users "session key") and store the ciphertext in the users PHP session (file on the server) and the encryption key as a client cookie. This ensures only the user can decrypt their own session. Session keys are generated every login and the data deleted when the user logs out.
- Client login items (passwords) are encrypted with the AES master key with a unique salt.
