### ISSUE TITLE
Feature request: Contact option

### ISSUE THREAD

**Issue by aftechro** [johnnyq/itflow#268]
When creating the company, on the contact section should be added the main company number and email address - call it $main_contact
so under the Client card on ticketing will be displayed the main phone number of the company. If the user doesnt have a DD number, the technician can just click on the main number associated with the client, and can then ask to be transferred to the contact

Alternatively, the main number can be added to contact card if no DD or mobile exists
- this will be helpful for the ticket contact details (once you`ll do the data base, i can do the rest :D )

- allow multiple primary contacts, also for ticketing system. This will be displayed on the Client card in ticketing, so the technician can take the right and fast decisions
       if($contact_id == $primary_contact){
       $approvers = "<small class='text-success'>$contact_name</small>";
       }else{
       $approvers = "<small class='text-danger'>Please add primary contacts</small>";
      }
  
![image](https://user-images.githubusercontent.com/38830718/149035961-af853254-699e-458f-8272-bed733c9580d.png)

**Comment by wrongecho** [comment]
For the phone element, we could possibly cover this under the primary location phone entry (and extend that to allowing a generic e-mail for the primary location as well maybe)? What do you think?
![location-phone](https://user-images.githubusercontent.com/32306651/149039135-98c99700-a302-4fd5-a3cc-79ebd2123979.png)

**Comment by aftechro** [comment]
Is not harm in having it, but from my experience at least, there are not so many companies with multiple locations, most ov them have single. Sure, you could have a company with primary as head office and secondary as warehouse and so on. So, it's good to have it, and use it where necessary 


Sent from Yahoo Mail on Android 
 
  On Tue, 11 Jan 2022 at 23:52, ***@***.***> wrote:   


For the phone element, we could possibly cover this under the primary location phone entry (and extend that to allowing a generic e-mail for the primary location as well maybe)? What do you think?


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wrongecho** [comment]
My suggestion was to populate the primary location with the phone number (as the code and database fields are already there for this) and then we can just add some code in the ticket client field to show the primary location / main contact number? :)

Here's what I mean:
![location-phone-2](https://user-images.githubusercontent.com/32306651/149040800-aef5d694-3ca7-4166-91ed-84c6d954f3a4.png)

**Comment by johnnyq** [comment]
@wrongecho That looks and sounds good to me. The primary location should be the main number

**Comment by aftechro** [comment]
Ohh yeah, that's sounds good. Didn't understand it first, late night here haha

Sent from Yahoo Mail on Android 
 
  On Wed, 12 Jan 2022 at 4:01, ***@***.***> wrote:   


@wrongecho That looks and sounds good to me. The primary location should be the main number

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wrongecho** [comment]
Looks good!
![contact](https://user-images.githubusercontent.com/32306651/151678716-e6d57714-6d6c-45a8-b631-7b8068c2e9e5.png)
