### ISSUE TITLE
Feature Request: Auto Update Option

### ISSUE THREAD

**Issue by athornfam2** [johnnyq/itflow#269]
Feature I think is pretty self explanatory...

It would be nice to have a bash script to git or wget download and execute to update the installation or have a set of solid update instructions.

An example would be bookstack. Pretty easy for me to setup a cron job to auto update every few weeks non-production and then update on production.

**Comment by johnnyq** [comment]
Hi @athornfam2 I agree although we are still Beta and hope to have easy upgrade paths in the future. Currently you can upgrade ITFlow by going to settings > General > Update Although it currently doesn't update database table structure as of yet. We also do not recommend automatic updates as sometimes auto updates can break things.

**Comment by johnnyq** [comment]
closing as this is already set for 1.0
