### ISSUE TITLE
Tracking installs

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#288]
As discussed, it'd be a good idea to get some vague numbers over time of installations. This needs to be **strictly opt-in** to protect privacy. 
Might be best to do on the initial setup, at least at first? Can be something as simple as a GET request to an itflow.org page?

Data to collect:
- Current version (we need to add versioning to the database?)
- Country/language of install -- Could possibly get this from the IP address that reports the install (but we'd then need to determine the country from the IP and then store that and not the IP)

**Comment by johnnyq** [comment]
That sounds good I have something like this in place for SimpNAS a project that I haven't worked on for a very long time. I can take on this one if you haven't already?

**Comment by johnnyq** [comment]
5fdf956eb44a1cb81da1e4671c88311619214c7a

**Comment by johnnyq** [comment]
It has been done.

I setup a URL https://telemetry.itflow.org This is where the data will be sent if a user opts for basic data collection during setup. This should help track the numbers of installs along with some basic geographic data along with comments to help further improve ITFlow.

I will upload telemetry source code to github tomorrow

**Comment by wrongecho** [comment]
Great work!
