### ISSUE TITLE
Bug: Hide Password by default for software and Logins OTP Key

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#292]
Hi,

I know, it's not issues. If it is not the right place, let me know.

Can I suggest to hide by default some password fields?

Some pages where I saw clear text passwords:
Assets \ Software \ Login
Assets \ Logins \OTP Secret Key

Other request: 
Display Global vendors in CLIENTS. May be diplay (global) at the end or split drop list "Global/Client".

Regards,

Philippe

**Comment by Wikiphil** [comment]
About the common vendors, sorry, I see the request #101.

Regars.

**Comment by johnnyq** [comment]
I see it I will get those fixed good catch

**Comment by Wikiphil** [comment]
Good. Let me know if you need a tester!

**Comment by johnnyq** [comment]
I nominate you as the bug tester. Much appreciated. just keep it one bug per issue and we'll get them closed out
