### ISSUE TITLE
Bug: Invoice / Quotes Footer - Displaying all in 1 line HTML and only displaying 2 lines for PDF

### ISSUE THREAD

**Issue by crnbezuidenhout** [johnnyq/itflow#300]
The Footer of both the Invoice & Quotes does not reflect the full Terms or description added into the settings field, it only displays one line...

Downloaded Invoice:
![image](https://user-images.githubusercontent.com/97749452/149918175-60a9061c-79e0-4414-b032-b320a7f3497a.png)

Settings Page
![image](https://user-images.githubusercontent.com/97749452/149918268-a989663e-9eea-44c0-b613-2af422085fa5.png)

**Comment by johnnyq** [comment]
I see what you mean. We'll open this as a bug and see if we can fix this Thank you for reporting

**Comment by johnnyq** [comment]
Working on the PDF, also there are other places this may need fixed will comb through the code

**Comment by johnnyq** [comment]
Okay should be fixed now

80355417faca00e62fb0f2f4c6c88fbc8c551dad


We also fixed new line issues for item description and notes for invoices/ Recurring and Quotes

Thank you
