### ISSUE TITLE
Can't login after fresh installation

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#301]
Hi,

For a couple days, with the latest Git pull, I've had to redo my setup. I thought that it was my server. So, I restarted a new VM Ubuntu.

Ubuntu 20.04 LTS
MariaDB PHP and Apache2, basic configurations
No custom configuration in PHP or Apache, just as is.

I'm able to access the web interface to configure the ITFlow basic configurations.

![Dashboard](https://user-images.githubusercontent.com/84292480/150063310-4700dc96-143d-4181-8b47-e907c5cd6065.png)

Login out and try to log back in... loops on the login screen. I really don't understand.

Here is the Apache error log:
Wed Jan 19 04:02:23.859717 2022] [mpm_prefork:notice] [pid 58474] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Jan 19 04:02:23.860358 2022] [core:notice] [pid 58474] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 19 04:06:08.577688 2022] [php7:warn] [pid 58477] [client 10.250.10.90:63077] PHP Warning:  include(config.php): failed to open stream: No such file or directory in /var/www/html/header.php on line 3
[Wed Jan 19 04:06:08.577928 2022] [php7:warn] [pid 58477] [client 10.250.10.90:63077] PHP Warning:  include(): Failed opening 'config.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/header.php on line 3
[Wed Jan 19 04:06:08.583520 2022] [php7:notice] [pid 58477] [client 10.250.10.90:63077] PHP Notice:  Undefined variable: config_https_only in /var/www/html/check_login.php on line 6
[Wed Jan 19 04:08:08.653785 2022] [php7:notice] [pid 58479] [client 10.250.10.90:63219] PHP Notice:  Undefined index: current_code in /var/www/html/login.php on line 34, referer: http://10.250.5.1/login.php
[Wed Jan 19 04:08:24.333929 2022] [php7:notice] [pid 61183] [client 10.250.10.90:63316] PHP Notice:  Undefined index: logged in /var/www/html/check_login.php on line 19
[Wed Jan 19 04:08:31.556459 2022] [php7:notice] [pid 58480] [client 10.250.10.90:63335] PHP Notice:  Undefined index: current_code in /var/www/html/login.php on line 34, referer: http://10.250.5.1/login.php
[Wed Jan 19 04:08:32.067434 2022] [php7:notice] [pid 58480] [client 10.250.10.90:63335] PHP Notice:  Undefined index: logged in /var/www/html/check_login.php on line 19, referer: http://10.250.5.1/login.php
[Wed Jan 19 04:15:35.273456 2022] [php7:notice] [pid 61217] [client 10.250.10.90:63755] PHP Notice:  Undefined index: logged in /var/www/html/check_login.php on line 19
[Wed Jan 19 04:15:46.137745 2022] [php7:notice] [pid 58479] [client 10.250.10.90:63773] PHP Notice:  Undefined index: current_code in /var/www/html/login.php on line 34, referer: http://10.250.5.1/login.php
[Wed Jan 19 04:15:46.619149 2022] [php7:notice] [pid 58479] [client 10.250.10.90:63773] PHP Notice:  Undefined index: logged in /var/www/html/check_login.php on line 19, referer: http://10.250.5.1/login.php
[Wed Jan 19 04:19:34.364735 2022] [php7:notice] [pid 58481] [client 10.250.10.90:63992] PHP Notice:  Undefined index: current_code in /var/www/html/login.php on line 34, referer: http://10.250.5.1/login.php
[Wed Jan 19 04:19:34.844136 2022] [php7:notice] [pid 58481] [client 10.250.10.90:63992] PHP Notice:  Undefined index: logged in /var/www/html/check_login.php on line 19, referer: http://10.250.5.1/login.php

Is there something I'm doing wrong? 

I think I'll try to pull an older Git if it is possible. Last week, with the same kind of installation, access was working fine.

Thanks.

**Comment by Wikiphil** [comment]
I reseted to 01c5ba5, "Create LICENCSE", in that version, I'm able to login.

**Comment by wrongecho** [comment]
Hey

> [Wed Jan 19 04:06:08.583520 2022] [php7:notice] [pid 58477] [client 10.250.10.90:63077] PHP Notice: Undefined variable: config_https_only in /var/www/html/check_login.php on line 6

Does your config.php include a variable called config_https_only ?
If not, go ahead and set it (or rename your config, reinstall and then merge the changes together).

**Comment by Wikiphil** [comment]
Yes, buy I'm using it http, I didn't installed any SSL for the moment.

![config php](https://user-images.githubusercontent.com/84292480/150127774-c3500bc5-eeef-4373-815f-f03b7b1838de.png)

**Comment by Wikiphil** [comment]
Ok, good. For test environment, putting "config_https_only" to FALSE workaround my issue.

**Comment by Wikiphil** [comment]
Thanks for the tip!

**Comment by wrongecho** [comment]
Glad you got that sorted!
