### ISSUE TITLE
Ticket default view

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#303]
Can we make "Open Tickets" as default view when we click on "Tickets"

![Ticket-default-view](https://user-images.githubusercontent.com/84292480/150192184-a4a190bf-638f-48da-a8aa-3b18ba2db2d3.png)

When the DB will have 1000 tickets closed and few tickets open, I think it will be a better view.

**Comment by aftechro** [comment]
work in progress on Tickets section. New dashboard to be implemented. Adding few cards. 
Stuck with the right sql queries https://github.com/johnnyq/itflow/issues/298

**Comment by wrongecho** [comment]
@aftechro - I will leave you to this for now in that case.
I'm scratching my head trying to get the filters to work properly (on-hold tickets don't register as open either!!).

**Comment by aftechro** [comment]
yep, once the dashboard takes contour, we can then make sure the functionalities are there and work as should.

**Comment by wrongecho** [comment]
The main (all client) ticket view now defaults to open tickets only, with options for unassigned/my tickets!

![tickets](https://user-images.githubusercontent.com/32306651/155878558-99450aac-a0a6-43dc-9327-3f2e49f619a9.png)
