### ISSUE TITLE
Time tracking closed tickets

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#305]
Closed tickets continue to attempt to time-track
![tt](https://user-images.githubusercontent.com/32306651/150217284-2e84d0af-c9c5-4294-be44-23e7e22734d8.png)

**Comment by johnnyq** [comment]
Ill see if I can tackle this one

**Comment by johnnyq** [comment]
I think that should do it Ill monitor the Web Debug Console

**Comment by wrongecho** [comment]
Thanks :)
I only noticed it as my browser started to grind to a halt and the power usage went through the roof for it in task manager.

**Comment by johnnyq** [comment]
lol nice notice!! =]

**Comment by johnnyq** [comment]
Closing this off
