### ISSUE TITLE
Scheduled Tickets Management menu

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#310]
Added basic functionality for scheduled tickets in #254.

Need to add a menu to administer (update/delete) them. _Maybe a separate menu option for it like recurring invoices_.

**Comment by johnnyq** [comment]
I think a separate menu option would be best for this

**Comment by wrongecho** [comment]
Initial - #319

**Comment by johnnyq** [comment]
This is going to be great. We test client backups once every quarter this would be fantastic reminder for that. Thank you

**Comment by wrongecho** [comment]
Added the edit option in #344.

**To-do**
Add frequency:
- Quarterly
- 6 monthly

**Comment by wrongecho** [comment]
![scheduled_tickets](https://user-images.githubusercontent.com/32306651/155565000-df9bdb14-72e4-4bfd-8bd4-05704c4307ce.png)
