### ISSUE TITLE
Feature request: Login brute force protection

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#312]
Login brute force protection
A few ways we could do this, but by IP address would probably be perfectly fine. 
Could possibly use the existing logging - or just track failed login attempts in a new table and check that a particular IP hasn't failed more than X times in the last X mins before progressing the login request.

**Comment by johnnyq** [comment]
Very good idea! Maybe also have a 30 Min unblock window jsut in case someone really forgot their password

**Comment by johnnyq** [comment]
Works great so far! @wrongecho
