### ISSUE TITLE
Can't delete attached files in a Client

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#316]
Testing purpose, I added some files to a Client. Now, I can't delete it from the view.

![Attached-Files](https://user-images.githubusercontent.com/84292480/150621763-ec2ac3e6-c1ce-474e-9a72-d13780d12a4f.png)

How I delete them?

**Comment by wrongecho** [comment]
When I click on the **X** just to the right of the file name (at the bottom), the file disappears and I get an alert that says "File deleted" - What happens for you?

**Comment by Wikiphil** [comment]
Hahaha! I didn't the X at the bottom because of the picture itself. It works, but no notification about deletion.

Thanks.
