### ISSUE TITLE
Feature Request: Services

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#322]
So I know we track multiple asset types (assets themselves, logins, domains, etc) which is great but I think what truly makes a good documentation system is the ability to tie all that together - "Services".

A "Service" would be something like Active Directory, a web app, etc.
Attributes:
- Name
- Description
- Category
- Importance
- Notes

Linked/Related to:
- Asset(s) / Login(s)
- Vendor (if appropriate)
- Domain(s) / SSLs
- Backup by (asset)
- Almost anything else in ITFlow

To be honest, this would be relatively easy to add, the majority of the structure already exists. It'd just be associating assets/docs/vendors/etc with a service.

Let me know if you like the general idea of this?

![services](https://user-images.githubusercontent.com/32306651/150677933-bacea568-dfe5-42a0-a922-704a7fbc8962.png)

![services_view](https://user-images.githubusercontent.com/32306651/150678166-f13e47f6-2d74-4eac-9a5d-836025a8fed0.png)

**Comment by johnnyq** [comment]
This is idea is great! and it really does tie everything in real nice from the example screenshots! I'd deff say go for it. I really like the idea.

**Comment by wrongecho** [comment]
This is where I'm up to at the moment on the backend and displaying the data..
![Untitled](https://user-images.githubusercontent.com/32306651/150865239-b6c44951-d6e7-4abe-9794-57c4de55596a.png)

I've added commented out certificates, backup and services as "coming soon". 
- For certificates, I think these would really only be linked via a domain rather than linked by themselves. We can do both through -- thoughts?
- For backup, should this be it's own table or just a (varchar) field in the service table? I think for most setups this will just be something like "Datto" or whatever, and would be more useful to link to the doc/service article on that. Open to ideas?
- Services - I need to add a search to the services page for this link to be useful...work is ongoing :)

Oh and just the small task of writing the UI to add and edit.... We'll get there haha

**Comment by wrongecho** [comment]
This has been provisionally implemented. 
It is currently missing some features such as the linking of certificates, files, and URLs. These are to be added at a later date.

@johnnyq - In terms of URLs - do you think one URL per service is sufficient (stored in the services table along with the service name, desc, etc) or should we be able to link multiple URLs for each service (service_urls table)? If multiple URLs, should we pull these from asset logins/logins or allow users to specify urls (with a standalone urls table too)?

**Comment by johnnyq** [comment]
1. For Certificates: I would say both
2. I think backup should be its own varchar field within services which as you said can link back to a document called backup with more details on the backup.
3. URLs - I think we could pull these from client_logins would be sufficient

**Comment by wrongecho** [comment]
Backup PR submitted, certs & URL's left!

**Comment by wrongecho** [comment]
@johnnyq What are your thoughts on adding custom fields? I feel like it could be a nice to have but am struggling to see a use case that a note couldn't address?
