### ISSUE TITLE
Feature request: Client overview page

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#323]
I can see it's in the client routes, but wanted to formally request a client overview page as the initial client page.

This could include details like:
- Client brief overview (what they do, etc)
- Quick notes
- Recently updated records
- Primary contact(s)
- Upcoming expirations

**Comment by johnnyq** [comment]
This was on my list for awhile and would be a fantastic addition

**Comment by wrongecho** [comment]
Thanks for adding this, looking good!

![overview](https://user-images.githubusercontent.com/32306651/158067362-4f5e5f16-a7f3-4e9b-87de-5b12eaf326de.png)
