### ISSUE TITLE
Cleanup: File Structure Renaming

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#324]
For Tracking

Rename Files to meet a better structure hierarchy allow for easier development and organization

This organizes the **entity** with it's **functions** so when working with an entity you don't have to scroll through the file structure to find all the functions based off that entity when developing.

Renaming examples.
- add_user_modal.php ---> user_add_modal.php
- edit_user_modal.php ---> user_edit_modal.php
- add_contact_modal.php ---> client_contact_add_modal.php
- add_location_modal.php ---> location _add_modal.php

users.php will still be users.php 
client_contacts.php will still be the same
client.php etc

**Comment by Wikiphil** [comment]
Hi Johnny,

Is there a diagram somewhere showing relation between files and SQL Tables? And wich files refer/use other files?

**Comment by johnnyq** [comment]
No nothing like that, although a DB Structure Relation Diagram would be nice. I think PHPmyAdmin can do this.

**Comment by johnnyq** [comment]
Done 278b243e7c804eb96a032f69cd02fbaae24956d6

**Comment by wrongecho** [comment]
Woooooo!!!
