### ISSUE TITLE
Feature request: Quote add items

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#325]
In the quote, actually we have to type down everything. Instead of having a blank line and fill all fields, can we have a button "Add item"? It will open a box, from there we can have the option to choose to fill the form or choose from the global product list?

![20220123-quote1](https://user-images.githubusercontent.com/84292480/150693329-8890976f-203d-41ce-a36c-6496f08fec2b.png)

At this moment, we will have "common part numbers" between all Clients and Quotes. More easy to make orders to distributors.

**Comment by Wikiphil** [comment]
As well, pre-configure Description, Price and Tax fields from products tables. 

Do not make link between tables, just take the content on the products table to populate the fields in the quote.

**Comment by wrongecho** [comment]
Heyy,
I'm not sure exactly what you mean. You can already choose items from the product list - I added this recently in #291! If you type the first couple of characters of a product name you can click and it'll fill in/complete the details.

![quote-auto-type](https://user-images.githubusercontent.com/32306651/150693474-6a1056ea-b5b6-406f-a01e-fc4ce3c3793f.png)

Or do you mean something else?

**Comment by Wikiphil** [comment]
Ok, Browser Auto-completion makes me crazy! Most of the users will have it enabled.

![20220123-quote2](https://user-images.githubusercontent.com/84292480/150694063-a63027fb-f375-4261-b755-2c7ffde53a36.png)

Tax is not selected

![20220123-quote3](https://user-images.githubusercontent.com/84292480/150694151-dfdf0a99-bdb9-4018-940c-ce3882a70ee9.png)

But, good job! I didn't see this auto-completion field.

**Comment by wrongecho** [comment]
Glad you found it!

Yeah, tax isn't stored in the products table in an easily usable way so I haven't added it for the moment. It's stored referencing the tax ID rather than the tax % itself (in a separate table).
We might be able to add tax eventually - it's just an extra query that has to be called and then formatted into JSON nicely along with the rest of the data for jQuery to fill the form properly.

**Comment by Wikiphil** [comment]
Feel free to close this issue if you want. 

Thanks.

**Comment by johnnyq** [comment]
Closing Thank @wrongecho
