### ISSUE TITLE
Client Access

### ISSUE THREAD

**Issue by crnbezuidenhout** [johnnyq/itflow#328]
Good Day All,

What is the purpose of the client access option under the users page?

- is it for the client to gain access to their information and spending?

![image](https://user-images.githubusercontent.com/97749452/151420714-875b2e5b-6bd7-49e5-8d94-0613d9692d88.png)

- if so, I have created a test account with the client roll, the client is able to access his/her page yes, but also able to see the main company page, with all of its clients, expenses, payments received, vendors and so forth...
- Should this not maybe be restricted to only the clients page being:
![image](https://user-images.githubusercontent.com/97749452/151421939-c9b2c57c-65c8-4bf6-90f1-c12ff909bf9c.png)

Ive tried to provide as much info as possible to make sense in this reqeust, see below...

![image](https://user-images.githubusercontent.com/97749452/151421079-8e2b947a-219d-4b93-a4a9-b12324c35a35.png)
![image](https://user-images.githubusercontent.com/97749452/151421300-2400ef5f-825f-42ea-afd6-14c9e7c63e7b.png)
![image](https://user-images.githubusercontent.com/97749452/151421524-b5912871-c98a-4c75-8e5e-250f697fdd7f.png)

**Comment by wrongecho** [comment]
This feels related to #321

**Comment by crnbezuidenhout** [comment]
Hi yes, its the same, didn't notice that it was already raised...

Thanks 😊 and Great work thus far...

**Comment by wrongecho** [comment]
No worries! :)

If you do notice any bugs/issues/requests that haven't yet been raised, please do raise an issue! Just be mindful that this is being built in peoples free time so there's little guarantee as to when things will actually get fixed/added :)
