### ISSUE TITLE
DB update after git pull: example Certificate management

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#331]
I've updated my directory with git pull. Great.

Now seaking for new features or bugs. I know my MariaDB is not up to date even if it says "Congratulations you are up to date!" under "Update" tab in Settings.

In certificates Table, there is a new column called "certificate_domain_id" that is not in my current Database.
![20220129-SQL-DB sql-file](https://user-images.githubusercontent.com/84292480/151668033-ff3476f5-c1b1-46dd-88c5-d997855d13d4.png)

My current DB
![20220129-SQL-CertificatesTable](https://user-images.githubusercontent.com/84292480/151668041-9fc6593b-c586-4bbb-9bcc-659474abb53d.png)

So, what it the procedure to merge new changes in DB structure?

**Comment by Wikiphil** [comment]
At the same time, there is a error logged in Apache Error logs:

[Sat Jan 29 15:56:25.753221 2022] [php7:notice] [pid 338757] [client 10.250.10.90:56120] PHP Notice:  Undefined index: certificate_domain_id in /var/www/html/client_certificates.php on line 103, referer: https://itflow1.xxxxxxxxx.ca/client.php?client_id=2&tab=certificates
sh: 1: gitrev-parse: not found

This is where I noticed the missing DB configurations.

**Comment by wrongecho** [comment]
Hey!

I don't think the database structure updater actually works at the moment.. You're correct - I added a new column so we can link the certificate to a domain.

Looks like you're using phpMyAdmin so should be easy.
- Open the Certificates table
- Click Structure
- Select "Add 1 column after certificate_archived_at" (what column it is after doesn't actually matter) and hit Go
  -  For name put certificate_domain_id
  -   For Type leave as INT
  -  For Length 11 is fine
  -  Tick the NULL box
  -  Click Save

![cert_db](https://user-images.githubusercontent.com/32306651/151669123-d928fef1-4690-4925-83b0-c844c1aad22a.png)

If you have any issues let me know :)

**Comment by johnnyq** [comment]
Hi @Wikiphil DB Structure does not get updated with ITFlow update, you will have to add fields manually for now. Keep an eye out for the db.sql file to change

**Comment by Wikiphil** [comment]
Ok, it fixes the error on certificates screen. 

Thanks
