### ISSUE TITLE
Itflow Use cases

### ISSUE THREAD

**Issue by ugintl** [johnnyq/itflow#332]
I request users to share different use cases of itflow. It will make easier for people to decide whether it is right for them or not or in what ways it can benefit. Thanks

**Comment by wrongecho** [comment]
Hello, @ugintl!

I think the general use case for ITFlow is that you're the owner of an IT Managed Service provider and need a tool to help manage your work. ITFlow allows you to track all your client's information (people, assets, documentation, finances, etc.) in one place.

Alternatively, you could probably use this for an internal IT department. You'd just add your company as the only client and just use which features apply to you.

Have you tried out the demo at all? Details are on the README.

**Comment by wrongecho** [comment]
Please feel free to discuss this further at https://forum.itflow.org/
