### ISSUE TITLE
Feature Request: Scheduled Tickets and Checklists

### ISSUE THREAD

**Issue by andrejtr** [johnnyq/itflow#352]
Hi,

in my experience every company does server maintenance, it would be a good feature if you could introduce scheduled tickets that open e.g. once a month and have a checklist attached to them.

The checklist can be ticked off and as soon as you have ticked off the last item, everything you have ticket off is saved as a comment that you could add to the invoice as a description.

**Comment by wrongecho** [comment]
Heyy @andrejtr!

I've recently added scheduled tickets and have plans to add "workflows" / checklists. In fact, I had the exact same thoughts as you! - #238

We'll get there eventually!! :)
