### ISSUE TITLE
Error 500 after upgrade or new installation

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#370]
Hi,

I've done a GIT PULL today and I got an error 500 before the login page. So, I flushed the folder and DB, same result.

In Apache log I got this error:
[Sun Feb 20 22:40:07.047096 2022] [php7:error] [pid 2663] [client 10.250.10.90:55611] PHP Fatal error:  Uncaught Error: Call to undefined function numfmt_create() in /var/www/html/check_login.php:93\nStack trace:\n#0 /var/www/html/header.php(9): include()\n#1 /var/www/html/dashboard_financial.php(1): include('/var/www/html/h...')\n#2 {main}\n  thrown in /var/www/html/check_login.php on line 93, referer: https://itflow1.-----.ca/login.php

I understand that it is coming from an entry that is not existing in my DB. Any idea?

Phil

**Comment by wrongecho** [comment]
Ran into this earlier. You need to install/activate a php extension most likely: php-intl

**Comment by Wikiphil** [comment]
You're right! Installed the php-intl and restart Apache, it works! :-)
