### ISSUE TITLE
Images inserted into docs/tickets don't save

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#377]
Looks like images are stripped from documents/tickets, likely due to HTMLPurifier?

**Comment by johnnyq** [comment]
Oh no this is because i think it strips the image tag. HTML/Purifier may need configured to allow images

**Comment by wrongecho** [comment]
When uploading images via summer note they seem to just be converted to base64. This probably isn't ideal as then we're storing images in the database rather than as files - larger images seem to fail for me. The workaround seems to be to force images to be uploaded and then link to them in Summernote - https://stackoverflow.com/questions/21628222/summernote-image-upload.

I've raised a PR to allow the images to work properly, we can look into a longer term solution in the future I guess?

**Comment by johnnyq** [comment]
yes I agree that images should be a file. The database could grow quite large, but thanks for the quick fix
