### ISSUE TITLE
IP Spoofing

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#385]
In functions.php, the get_ip function first looks for several HTTP headers, and only if they are not present will it return the REMOTE_ADDR. 
```php
function get_ip() {
    $mainIp = '';
    if (getenv('HTTP_CLIENT_IP'))
        $mainIp = getenv('HTTP_CLIENT_IP');
    else if(getenv('HTTP_X_FORWARDED_FOR'))
        $mainIp = getenv('HTTP_X_FORWARDED_FOR');
    else if(getenv('HTTP_X_FORWARDED'))
        $mainIp = getenv('HTTP_X_FORWARDED');
    else if(getenv('HTTP_FORWARDED_FOR'))
        $mainIp = getenv('HTTP_FORWARDED_FOR');
    else if(getenv('HTTP_FORWARDED'))
        $mainIp = getenv('HTTP_FORWARDED');
    else if(getenv('REMOTE_ADDR'))
        $mainIp = getenv('REMOTE_ADDR');
    else
        $mainIp = 'UNKNOWN';
    return $mainIp;
}
```

In a typical setup with no WAF/reverse proxy, we should **only** be looking at the REMOTE_ADDR to find the client's IP address, all other variables should **not** be trusted.

In a setup with a reverse proxy, we should allow the app owner/admin to define what value to trust (e.g. with Cloudflare this would be _CF-Connecting-IP_).

In the current setup, I am able to spoof these headers and make the IP logged whatever I like. This has implications for auditing/logging as well as login brute force protection.

I think we should by default use REMOTE_ADDR, but allow the user to customize in the event the server is behind a reverse proxy.

![burp](https://user-images.githubusercontent.com/32306651/155884395-845a8141-9312-4017-a046-0d0307be77f6.png)

![ip-spoof](https://user-images.githubusercontent.com/32306651/155884360-80e261c3-6066-4322-be47-bfbd19154ff1.png)

**Comment by johnnyq** [comment]
Nice find! @wrongecho HestiaCP does proxying by default. Nginx acts as a proxy / Static Asset Cache and passes data to Apache

**Comment by wrongecho** [comment]
@johnnyq, been thinking about this one. I like the idea of defaulting to using REMOTE_ADDR but allowing the user to specify for their use case in case they are using something like HestiaCP, Cloudflare, etc. Do you think this should be a setting in the database (and UI) or in the config.php file?

**Comment by johnnyq** [comment]
@wrongecho I think we should follow what other apps are doing without adding additional settings if we can help it. I haven't quite got a chance to look into it any deeper than that though. I'm not quite sure what the best practice is here and would like it to be as plug and play as possible.

**Comment by johnnyq** [comment]
How about this function
https://www.codexworld.com/how-to/get-user-ip-address-php/

```
function getUserIpAddr(){
    if(!empty($_SERVER['HTTP_CLIENT_IP'])){
        //ip from share internet
        $ip = $_SERVER['HTTP_CLIENT_IP'];
    }elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
        //ip pass from proxy
        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
    }else{
        $ip = $_SERVER['REMOTE_ADDR'];
    }
    return $ip;
}

echo 'User Real IP - '.getUserIpAddr();
```

Would this correct the spoofing issue @wrongecho ?

**Comment by johnnyq** [comment]
actually found one better that prevents spoofing

https://www.benmarshall.me/get-ip-address/
```

<?php
/**
 * Return the current visitor's IP address.
 * 
 * @since x.x.x
 * @link https://www.benmarshall.me/get-ip-address/
 * 
 * @return string|false The current visitor's IP address, false if unavailable.
 */
if ( ! function_exists( 'get_ip_address' ) ) {
  function get_ip_address() {
    foreach([
      'HTTP_CLIENT_IP', 
      'HTTP_X_FORWARDED_FOR', 
      'HTTP_X_FORWARDED', 
      'HTTP_X_CLUSTER_CLIENT_IP', 
      'HTTP_FORWARDED_FOR', 
      'HTTP_FORWARDED', 
      'REMOTE_ADDR'
    ] as $key ) {
      if ( array_key_exists( $key, $_SERVER ) === true ) {
        foreach( explode( ',', $_SERVER[ $key ] ) as $ip_address ) {
          $ip_address = trim( $ip_address );
          if ( filter_var( 
            $ip_address, 
            FILTER_VALIDATE_IP, 
            FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false 
          ) {
            return $ip_address;
          }
        }
      }
    }
  }
}
```

**Comment by wrongecho** [comment]
Hey @johnnyq!

Been a very busy week!!

Thanks for looking into this. I gave that second sample a go on my dev setup and it just seems to return false - presumably as it's a local IP address? Adding a Client-IP header of 8.8.8.8 then shows my IP as being 8.8.8.8. I think the issue with this code is that it attempts to check for IP spoofing in user headers only by checking if there is a valid IP address (and not in a private/reserved range).
![image](https://user-images.githubusercontent.com/32306651/158052064-bc8722a0-6f92-419c-b68f-9f88752decd8.png)


I've done some research and am still of the opinion that the only variable that should be trusted by default is the `$_SERVER['REMOTE_ADDR']`. 
I've attached the options of how Wordfence, a WordPress security plugin, handles IP addresses by default. I'm still a little unclear on exactly what the first option means, it seems like they use PHP's `REMOTE_ADDR` but skip it if it's a local IP or something (to try and account for reverse proxies like HestiaCP).

![wordfence](https://user-images.githubusercontent.com/32306651/158052019-de85d04c-5cf3-402e-9d62-55fb77177247.png)


That post on benmarshall.me seems to have a limited understanding of what a VPN is and based off the code seems to believe VPN providers put the user's IP addresses in the Client-IP / Forwarded-For headers. It does warn "It will not protect you from the 0.1% of malicious users looking to abuse your system by injecting their own request headers" - I think we need to focus on this "0.1% of malicious users" as ITFlow will be storing pretty sensitive information. It might even be arguable that having no IP logging is better than having spoofable IP logging as it introduces a huge element of doubt.

We could possibly try and check if `$_SERVER['REMOTE_ADDR']` is a local IP and then if it is move onto the Client-IP header, etc, but this still would be an issue for anyone running ITFlow in a LAN.

I'm not closed off to ideas, but I'm struggling to think of a solution that isn't to only use `$_SERVER['REMOTE_ADDR']`, and allowing the admin to specify the header to trust if they are using a proxy. Anything else has the potential to compromise security.

**Comment by johnnyq** [comment]
I think we should go with the idea of the admin choosing at this point. We could have it list the options (radio Button like Wordpress) with the detected IP for each option and have the Admin select the one that shoes their public IP or if its LAN Only choose LAN only option.

**Comment by johnnyq** [comment]
Closing as we have come to a conclusion and @wrongecho did a pull to correct the issue
