### ISSUE TITLE
Client Export to PDF doesn't work

### ISSUE THREAD

**Issue by wrongecho** [johnnyq/itflow#395]
When on a client page, the Export PDF (with/without passwords) just shows a blank page, with the Javascript source. No download seems to be presented.

**Comment by wrongecho** [comment]
Looking like an issue on my end, unsure what exactly. Thanks for checking.

**Comment by johnnyq** [comment]
Fixed Thanks for pointing that out @asasin114

**Comment by asasin114** [comment]
Confirmed fixed!
