### ISSUE TITLE
Send Email Continuous Loop

### ISSUE THREAD

**Issue by hotheadhacker** [johnnyq/itflow#397]
Whenever any event triggers that involves sending a mail or test mail (I have correct config of mail imported) it triggers an infinite loading loop and then force logout

**Comment by wrongecho** [comment]
Hey @hotheadhacker, thanks for getting in touch.

I'm having trouble replicating this, mail seems to work OK for me at the moment.

I'd recommend posting the latest entries in the PHP error log after you send the e-mail to see if we can work out the problem.

**Comment by johnnyq** [comment]
I am unable to replicate this as well.

**Comment by hotheadhacker** [comment]
> Hey @hotheadhacker, thanks for getting in touch.
> 
> I'm having trouble replicating this, mail seems to work OK for me at the moment.
> 
> I'd recommend posting the latest entries in the PHP error log after you send the e-mail to see if we can work out the problem.

Thanks will be back with my error logs

**Comment by johnnyq** [comment]
Will close this out for now @hotheadhacker you may use our forums [forum.itflow.org](forum.itflow.org) further support.
