### ISSUE TITLE
Recurring Invoices - Chron Job?

### ISSUE THREAD

**Issue by iSparkySystems** [johnnyq/itflow#403]
Thank you for all your time and effort on superb software.

With recurring invoices for example are we supposed to set a chron job in place?

Sorry if I missed it - but I could not see this requirement so a little fuzzy if it will work - like magic?

**Comment by johnnyq** [comment]
Hi @iSparkySystems Thank you for your interest in ITFlow.
Yes you will need to run a cron job daily for recurring invoices and for alerts to work. You will also need to configure mail as well so it can send out the new recurring invoice to the client.

see Part 2 here for Cron configuration

[https://itflow.org/docs.php?doc=alerts](https://itflow.org/docs.php?doc=alerts)

**Comment by iSparkySystems** [comment]
You are a super star. Will do - thank you so much for that fast response.
