### ISSUE TITLE
Invoke POST method for Create via API

### ISSUE THREAD

**Issue by MikroT** [johnnyq/itflow#407]
Hi, first of all you are making a good job, so many thanks for it!

I'm trying to add assets using API by this powershell command

Invoke-RestMethod -Method 'Post' -Uri "http://itflow.mycompany.com/api/v1/assets/create.php?api_key=MYAPIKEY&asset_name=test&asset_type=Desktop&asset_client_id=2&company_id=1&"

Still receive this message
success message
------- -------
False   Auth success but insert query failed, ensure required variables are provided and database schema is up-to-date.

I also tryed to add all variables but the issue continue.

where is my mistake?

**Comment by wrongecho** [comment]
Hey!

Thanks again for checking out ITFlow.

I think we figured this out in Discord, but I've updated the documentation for future reference - https://itflow.org/docs.php?doc=assets

```
$uri = "http://127.0.0.1/itflow/api/v1/assets/create.php"

$body = @"
{
    "api_key" : "3iVeTipINS9eDGpm",
    "asset_name" : "Sample Laptop",
    "asset_type" : "Laptop",
    "asset_make" : "Dell",
    "asset_model" : "Optiplex",
    "asset_serial" : "Abc123",
    "asset_os" : "Win 10",
    "asset_ip" : "",
    "asset_mac" : "",
    "asset_purchase_date" : "",
    "asset_warranty_expire" : "",
    "install_date" : "",
    "asset_notes" : "",
    "asset_meshcentral_id" : "",
    "location" : "",
    "vendor" : "",
    "contact" : "",
    "network" : "",
    "client_id" : "1"
}
"@

Invoke-RestMethod -Method Post -Uri $uri -Body $body

success count data             
------- ----- ----             
True    1     {@{insert_id=42}}
```
