### ISSUE TITLE
Feature Request: Implement type ahead feature in Invoice items

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#42]
this will grab data from the products table as you type in the item box (Type ahead feature) Which will also Fill in the description and price from the products table to the Items table of the invoice/quote/recurring invoice

**Comment by johnnyq** [comment]
done

**Comment by johnnyq** [comment]
This does not work right plus it needs to grab the cost of the product and enter in the price field

**Comment by johnnyq** [comment]
This will require a bit of Javascript im going to clue @wrongecho in to possibly take a look at to see how he would approach this.
This would use a typeahead approach

**Comment by wrongecho** [comment]
Going to look further into this.
