### ISSUE TITLE
Create a Website and forum for this project

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#50]
just as it says

**Comment by johnnyq** [comment]
Looking for assistance on this part

**Comment by nickkecooper** [comment]
Wouldn't mind helping out on this end.

**Comment by johnnyq** [comment]
That would be Super! It would be very much appreciated. I can spin you up a web host on our infrastructure. I don't have a domain or name for the project yet so its still up in the air. At the very least I can create a temporarily sub domain and we can use that to build the site.

**Comment by afsound** [comment]
I can also help you, let me know what else you need. Hosting, domain let me know :D

**Comment by johnnyq** [comment]
Hi @afsound I really appreciate your offer on hosting. We are mainly looking for someone that can design a website that showcases ITFlow. That site would need to be static and not rely on any server side dynamic languages. So just plain HTML5/CSS3/Javascript.

**Comment by afsound** [comment]
Sure, i can help on that part also.

**Comment by johnnyq** [comment]
Fantastic! this will be a giant help. Ill assign this issue to you in the time being. I really appreciate the help =]

**Comment by johnnyq** [comment]
Website and Forum has been started using our custom CMS that is opensource as well
