### ISSUE TITLE
Auto Fetch Domain Expire Date

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/itflow#57]
Auto Fetch Domain Expire date when clicked

**Comment by afsound** [comment]
You can have something like this:

domain lists
![image](https://user-images.githubusercontent.com/38830718/105827408-de69db80-5fb9-11eb-85cc-31565867ee94.png)

domain data
![image](https://user-images.githubusercontent.com/38830718/105827709-39033780-5fba-11eb-978c-0122791ac864.png)

and pull the whois data if possible
![image](https://user-images.githubusercontent.com/38830718/105827886-6d76f380-5fba-11eb-95e8-771b6932e8e0.png)

**Comment by aftechro** [comment]
Would you please do same also for the SSL Certificates? 
Thank you!

**Comment by johnnyq** [comment]
Good Idea This has been implemented 6fb0d32b526315025b780028739406764b9123a3

**Comment by johnnyq** [comment]
Closing as this has been completed with SSL

**Comment by aftechro** [comment]
so, managed to do the fetch for SSL expire and submitted pull request, have a look at that

also, i`ve played a bit and i managed to do this:

- if you add the data to domains section, the SSLs will be automatically added to Certificates and will show the data, so the user dont need to add data both in domain and certificates section

![image](https://user-images.githubusercontent.com/38830718/149604757-a83e03d7-ee28-43da-a68c-53a4c0f2eb8c.png)

Future to do:
- fetch domain expiry, registrar, hosting, NS servers and zone records
